### ISSUE TITLE
Error on creating a ManagedKubernetes Cluster

### ISSUE THREAD

**Issue by paolomainardi** [terraform-providers/terraform-provider-alicloud#1034]
### Terraform Version

0.11.7

### Affected Resource(s)

- alicloud_cs_managed_kubernetes

### Terraform Configuration Files

```hcl

resource "alicloud_vswitch" "vswitches" {
  count             = "${length(var.vswitch_ids) > 0 ? 0 : length(var.vswitch_cidrs)}"
  vpc_id            = "${var.vpc_id == "" ? join("", alicloud_vpc.vpc.*.id) : var.vpc_id}"
  cidr_block        = "${element(var.vswitch_cidrs, count.index)}"
  availability_zone = "${lookup(data.alicloud_zones.main.zones[count.index%length(data.alicloud_zones.main.zones)], "id")}"
  name              = "${var.vswitch_name_prefix == "" ? format("%s-%s", var.example_name, format(var.number_format, count.index+1)) : format("%s-%s", var.vswitch_name_prefix, format(var.number_format, count.index+1))}"
}

resource "alicloud_nat_gateway" "default" {
  count  = "${var.new_nat_gateway == true ? 1 : 0}"
  vpc_id = "${var.vpc_id == "" ? join("", alicloud_vpc.vpc.*.id) : var.vpc_id}"
  name   = "${var.example_name}"
  specification = "Small"
}

resource "alicloud_eip" "default" {
  count     = "${var.new_nat_gateway == "true" ? 1 : 0}"
  bandwidth = "${var.eip_bandwidth}"
}

resource "alicloud_eip_association" "default" {
  count         = "${var.new_nat_gateway == "true" ? 1 : 0}"
  allocation_id = "${alicloud_eip.default.id}"
  instance_id   = "${alicloud_nat_gateway.default.id}"
}

resource "alicloud_snat_entry" "default" {
  count             = "${var.new_nat_gateway == "false" ? 0 : length(var.vswitch_ids) > 0 ? length(var.vswitch_ids) : length(var.vswitch_cidrs)}"
  snat_table_id     = "${alicloud_nat_gateway.default.snat_table_ids}"
  source_vswitch_id = "${length(var.vswitch_ids) > 0 ? element(split(",", join(",", var.vswitch_ids)), count.index%length(split(",", join(",", var.vswitch_ids)))) : length(var.vswitch_cidrs) < 1 ? "" : element(split(",", join(",", alicloud_vswitch.vswitches.*.id)), count.index%length(split(",", join(",", alicloud_vswitch.vswitches.*.id))))}"
  snat_ip           = "${alicloud_eip.default.ip_address}"
}

resource "alicloud_cs_managed_kubernetes" "k8s" {
  name = "${var.name}"
  availability_zone = "${data.alicloud_zones.main.zones.0.id}"
  new_nat_gateway = false
  vswitch_ids = ["${length(var.vswitch_ids) > 0 ? element(split(",", join(",", var.vswitch_ids)), count.index%length(split(",", join(",", var.vswitch_ids)))) : length(var.vswitch_cidrs) < 1 ? "" : element(split(",", join(",", alicloud_vswitch.vswitches.*.id)), count.index%length(split(",", join(",", alicloud_vswitch.vswitches.*.id))))}"]
  worker_instance_types = ["${data.alicloud_instance_types.default.instance_types.0.id}"]
  worker_numbers = [2]
  key_name = "${alicloud_key_pair.k8s.key_name}"
  pod_cidr = "172.20.0.0/16"
  service_cidr = "172.21.0.0/20"
  install_cloud_monitor = true
  slb_internet_enabled = true
  worker_disk_category  = "cloud_efficiency"
  worker_disk_size  = "50"
}

```

### Debug Output

```
alicloud_cs_managed_kubernetes.k8s: Creating...
  availability_zone:           "" => "cn-shenzhen-c"
  install_cloud_monitor:       "" => "true"
  key_name:                    "" => "aliyun_k8s_key_pair"
  name:                        "" => "cluster-k8s"
  name_prefix:                 "" => "Terraform-Creation"
  new_nat_gateway:             "" => "false"
  pod_cidr:                    "" => "172.20.0.0/16"
  security_group_id:           "" => "<computed>"
  service_cidr:                "" => "172.21.0.0/20"
  slb_internet_enabled:        "" => "true"
  vpc_id:                      "" => "<computed>"
  vswitch_ids.#:               "" => "1"
  vswitch_ids.0:               "" => "vsw-wz97ptmmopa17pjrr1bi9"
  worker_disk_category:        "" => "cloud_efficiency"
  worker_disk_size:            "" => "50"
  worker_instance_charge_type: "" => "PostPaid"
  worker_instance_types.#:     "" => "1"
  worker_instance_types.0:     "" => "ecs.n1.small"
  worker_nodes.#:              "" => "<computed>"
  worker_numbers.#:            "" => "1"
  worker_numbers.0:            "" => "2"
alicloud_cs_managed_kubernetes.k8s: Still creating... (10s elapsed)
alicloud_cs_managed_kubernetes.k8s: Still creating... (20s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* alicloud_cs_managed_kubernetes.k8s: 1 error(s) occurred:

* alicloud_cs_managed_kubernetes.k8s: Creating ManagedKubernetes Cluster got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"1155A090-BC2E-4F60-9F05-4068F2134866"}, HostId:"", Code:"ErrKubernetesAuditRoleNotAttach", Message:"service role not attach"}, StatusCode:400}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by xh4n3** [comment]
Hi @paolomainardi ,

There is an authorization you need to do before creating a cluster.

In short, you could try to create a managed cluster via the web console, the server will run an account pre-check for you. It requires you to authorize container service to access some of your products. After accept it, cancel the cluster creation. Then you can create cluster via terraform.

Please see this doc https://www.alibabacloud.com/help/doc-detail/86483.htm

**Comment by paolomainardi** [comment]
Thanks a lot, this is exactly what I did then, I forgot to update the issue.
Fun fact: With the same user I was able to create k8s clusters just some hours before.

**Comment by xh4n3** [comment]
@paolomainardi That's great!
Please feel free to report any issues on our k8s clusters via our online support system, where you can get faster responses.

**Comment by seitosan** [comment]
@paolomainardi  I had the same issue. I opened a ticket on alicloud support. 
The solution are to set policy and role to register the k8s roles

**Comment by paolomainardi** [comment]
It should be handled by terraform ?

**Comment by xiaozhu36** [comment]
HI @paolomainardi I am sorry to tell you that currently this progress only can be done by the Web Console and there is no api to support. The good new is that this step only need do once.

**Comment by xiaozhu36** [comment]
Closed by no reply.

**Comment by OUCHUNYU** [comment]
@paolomainardi Did you eventually solve the problem? How did you solve it? Would you mind sharing with me? I encountered the exact same error except that I'm using managed k8s.
```
Do you want to perform these actions in workspace "dev"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_cs_managed_kubernetes.managed_k8s: Creating...

Error: Creating ManagedKubernetes Cluster got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"B27BD654-1792-4EB3-922A-2A7A7D9C03F4"}, HostId:"", Code:"ErrKubernetesAuditRoleNotAttach", Message:"service role not attach"}, StatusCode:400}

  on main.tf line 6, in resource "alicloud_cs_managed_kubernetes" "managed_k8s":
   6: resource "alicloud_cs_managed_kubernetes" "managed_k8s" {


Releasing state lock. This may take a few moments...
```
I should have all of the policies and roles that were documented by Alicloud because they were auto-generated by Alicloud on their web console. However, by reading the error message, it feels to me that I'm missing a role or a policy somewhere.

**Comment by tsujp** [comment]
Terraform should handle this automatically, having to create resources and instantly delete them to enable automatic resource deployment is arbitrary, undocumented (except for this issue) and – therefore – unfriendly.

**Comment by xh4n3** [comment]
There's a note on the docs, the error currently cannot be resolved on the client side. 


> NOTE: You need to activate several other products and confirm Authorization Policy used by Container Service before using this resource. Please refer to the Authorization management and Cluster management sections in the Document Center.
> https://www.terraform.io/docs/providers/alicloud/r/cs_managed_kubernetes.html

**Comment by tsujp** [comment]
I've seen the note but it's still arbitrary that permissions must be manually granted for container service and not for other resources. Whatever backend API or change of behaviour needed to fix that should be implemented so that the resource can work predictably would be a nice QoL change.

**Comment by leonrodenburg** [comment]
I also ran into this issue. After the console created the role for me I took its contents and put it in Terraform. Then I removed the one created by the console, deployed again and the cluster was created successfully.

You can add the following resources to create the role (note this is 0.12, so if you are still on 0.11, you have to change it a little bit):
```
resource "alicloud_ram_role" "k8s-audit-role" {
  name     = "AliyunCSKubernetesAuditRole"
  document = <<EOF
  {
    "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Effect": "Allow",
        "Principal": {
          "Service": [
            "cs.aliyuncs.com"
          ]
        }
      }
    ],
    "Version": "1"
  }
  EOF
  description = "Allows Kubernetes to access other cloud resources"
  force = true
}

resource "alicloud_ram_role_policy_attachment" "k8s-audit-policy" {
  role_name = alicloud_ram_role.k8s-audit-role.name

  policy_name = "AliyunCSKubernetesAuditRolePolicy"
  policy_type = "System"
}
```

You will have to take an explicit dependency on the policy attachment in the cluster, so the role will be created before the cluster is deployed.

**Comment by ambar-cap** [comment]
Is there any update here? Should terraform be handling this or should Alicloud provide an api with which this can be handled?

**Comment by IronCore864** [comment]
I hate everything about it.

Really, some manual steps first to create a bunch of needed roles? You might as well use the UI to create the cluster.

And the error message is grammatically wrong:
- `ErrManagedKuberneteRoleNotAttach`: it's "kubernetes", not "kubernete". Did you invent kubernete Alibaba? Or are you Greek so that you can change their vocabulary?
- Then you have `ErrKubernetesAuditRoleNotAttach`: now you know it's "kubernetes" not "kubernete" Where is your consistency?
- Don't get me started on the "NotAttach" part: it's "NotAttached", and you are welcome.
- "Message: service role not attach": again.

Why don't you Just put Japanese in the error message. You won't get it right either anyway.

**Comment by leonrodenburg** [comment]
@IronCore864 Please have some respect.

You can just create the necessary roles in Terraform. I did that for a Serverless K8s cluster and it works without issues. If you are not sure which roles to create, go to the console, create a cluster and see which roles were created. Then port those to Terraform. Then for every other cluster you will ever want to create, you don't need to go to the console anymore. Problem solved. 

And as you can create these roles yourself, I don't see why this issue should still be open. The documentation could be better, I agree. But it's not something you cannot fix with infra-as-code.

```hcl
resource "alicloud_ram_role" "cs-cluster-role" {
  name        = "AliyunCSClusterRole"
  description = "Role assumed by clusters when creating / destroying resources"
  document    = <<EOF
    {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "cs.aliyuncs.com"
            ]
          }
        }
      ]
    }
EOF
}

resource "alicloud_ram_role_policy_attachment" "cs-cluster-role-policy-attachment" {
  policy_name = "AliyunCSClusterRolePolicy"
  policy_type = "System"
  role_name   = alicloud_ram_role.cs-cluster-role.name
}

resource "alicloud_ram_role" "cs-default-role" {
  name        = "AliyunCSDefaultRole"
  description = "Role assumed by Container Service when creating / destroying resources"
  document    = <<EOF
    {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "cs.aliyuncs.com"
            ]
          }
        }
      ]
    }
EOF
}

resource "alicloud_ram_role_policy_attachment" "cs-default-policy-attachment" {
  policy_name = "AliyunCSDefaultRolePolicy"
  policy_type = "System"
  role_name   = alicloud_ram_role.cs-default-role.name
}

resource "alicloud_ram_role" "cs-managed-k8s-role" {
  name        = "AliyunCSManagedKubernetesRole"
  description = "Role assumed by managed clusters when creating / destroying resources"
  document    = <<EOF
    {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "cs.aliyuncs.com"
            ]
          }
        }
      ]
    }
EOF
}

resource "alicloud_ram_role_policy_attachment" "cs-managed-k8s-role-policy-attachment" {
  policy_name = "AliyunCSManagedKubernetesRolePolicy"
  policy_type = "System"
  role_name   = alicloud_ram_role.cs-managed-k8s-role.name
}

resource "alicloud_ram_role" "cs-serverless-k8s-role" {
  name        = "AliyunCSServerlessKubernetesRole"
  description = "Role assumed by Serverless Kubernetes when creating / destroying resources"
  document    = <<EOF
    {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "cs.aliyuncs.com"
            ]
          }
        }
      ]
    }
EOF
}

resource "alicloud_ram_role_policy_attachment" "cs-serverless-k8s-policy-attachment" {
  policy_name = "AliyunCSServerlessKubernetesRolePolicy"
  policy_type = "System"
  role_name   = alicloud_ram_role.cs-serverless-k8s-role.name
}

resource "alicloud_ram_role" "eci-container-group-role" {
  name        = "AliyunECIContainerGroupRole"
  description = "Role assumed by ECI container groups when creating / destroying resources"
  document    = <<EOF
    {
      "Version": "1",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "eci.aliyuncs.com"
            ]
          }
        }
      ]
    }
EOF
}

resource "alicloud_ram_role_policy_attachment" "eci-container-group-policy-attachment" {
  policy_name = "AliyunECIContainerGroupRolePolicy"
  policy_type = "System"
  role_name   = alicloud_ram_role.eci-container-group-role.name
}
```

**Comment by IronCore864** [comment]
> @IronCore864 Please have some respect.
> 
> You can just create the necessary roles in Terraform. I did that for a Serverless K8s cluster and it works without issues. If you are not sure which roles to create, go to the console, create a cluster and see which roles were created. Then port those to Terraform. Then for every other cluster you will ever want to create, you don't need to go to the console anymore. Problem solved.
> 
> And as you can create these roles yourself, I don't see why this issue should still be open. The documentation could be better, I agree. But it's not something you cannot fix with infra-as-code.
> 
> ```terraform
> resource "alicloud_ram_role" "cs-cluster-role" {
>   name        = "AliyunCSClusterRole"
>   description = "Role assumed by clusters when creating / destroying resources"
>   document    = <<EOF
>     {
>       "Version": "1",
>       "Statement": [
>         {
>           "Action": "sts:AssumeRole",
>           "Effect": "Allow",
>           "Principal": {
>             "Service": [
>               "cs.aliyuncs.com"
>             ]
>           }
>         }
>       ]
>     }
> EOF
> }
> 
> resource "alicloud_ram_role_policy_attachment" "cs-cluster-role-policy-attachment" {
>   policy_name = "AliyunCSClusterRolePolicy"
>   policy_type = "System"
>   role_name   = alicloud_ram_role.cs-cluster-role.name
> }
> 
> resource "alicloud_ram_role" "cs-default-role" {
>   name        = "AliyunCSDefaultRole"
>   description = "Role assumed by Container Service when creating / destroying resources"
>   document    = <<EOF
>     {
>       "Version": "1",
>       "Statement": [
>         {
>           "Action": "sts:AssumeRole",
>           "Effect": "Allow",
>           "Principal": {
>             "Service": [
>               "cs.aliyuncs.com"
>             ]
>           }
>         }
>       ]
>     }
> EOF
> }
> 
> resource "alicloud_ram_role_policy_attachment" "cs-default-policy-attachment" {
>   policy_name = "AliyunCSDefaultRolePolicy"
>   policy_type = "System"
>   role_name   = alicloud_ram_role.cs-default-role.name
> }
> 
> resource "alicloud_ram_role" "cs-managed-k8s-role" {
>   name        = "AliyunCSManagedKubernetesRole"
>   description = "Role assumed by managed clusters when creating / destroying resources"
>   document    = <<EOF
>     {
>       "Version": "1",
>       "Statement": [
>         {
>           "Action": "sts:AssumeRole",
>           "Effect": "Allow",
>           "Principal": {
>             "Service": [
>               "cs.aliyuncs.com"
>             ]
>           }
>         }
>       ]
>     }
> EOF
> }
> 
> resource "alicloud_ram_role_policy_attachment" "cs-managed-k8s-role-policy-attachment" {
>   policy_name = "AliyunCSManagedKubernetesRolePolicy"
>   policy_type = "System"
>   role_name   = alicloud_ram_role.cs-managed-k8s-role.name
> }
> 
> resource "alicloud_ram_role" "cs-serverless-k8s-role" {
>   name        = "AliyunCSServerlessKubernetesRole"
>   description = "Role assumed by Serverless Kubernetes when creating / destroying resources"
>   document    = <<EOF
>     {
>       "Version": "1",
>       "Statement": [
>         {
>           "Action": "sts:AssumeRole",
>           "Effect": "Allow",
>           "Principal": {
>             "Service": [
>               "cs.aliyuncs.com"
>             ]
>           }
>         }
>       ]
>     }
> EOF
> }
> 
> resource "alicloud_ram_role_policy_attachment" "cs-serverless-k8s-policy-attachment" {
>   policy_name = "AliyunCSServerlessKubernetesRolePolicy"
>   policy_type = "System"
>   role_name   = alicloud_ram_role.cs-serverless-k8s-role.name
> }
> 
> resource "alicloud_ram_role" "eci-container-group-role" {
>   name        = "AliyunECIContainerGroupRole"
>   description = "Role assumed by ECI container groups when creating / destroying resources"
>   document    = <<EOF
>     {
>       "Version": "1",
>       "Statement": [
>         {
>           "Action": "sts:AssumeRole",
>           "Effect": "Allow",
>           "Principal": {
>             "Service": [
>               "eci.aliyuncs.com"
>             ]
>           }
>         }
>       ]
>     }
> EOF
> }
> 
> resource "alicloud_ram_role_policy_attachment" "eci-container-group-policy-attachment" {
>   policy_name = "AliyunECIContainerGroupRolePolicy"
>   policy_type = "System"
>   role_name   = alicloud_ram_role.eci-container-group-role.name
> }
> ```

Sorry if you think I'm being disrespectful. English isn't my native language and because of that, I may have chosen the wrong wording for it. I meant no harm, no disrespect in any means.

Also thanks for the code you pasted.

In fact, I know exactly how to solve this issue using terraform.

Before I met this issue, I already had had the solution all by myself using the same method mentioned in the previous reply in this topic.

From my point of view, however, that is simply not acceptable, regarding what I am doing is IaC.

My point is, what we are doing is IaC; the "go-to-the-console-and-create-a-cluster-manually-then-delete-it-later-to-find-out-what-resources-are-created-then-delete them-and-then-automate-it-in-your-code" simply isn't acceptable to me.

I'm willing to take a step back and assume that the above way of finding workaround is acceptable, but still, why don't just put it in the documentation in the first place, list what exactly are the dependencies, which roles, policies are needed?

I didn't mean any disrespect, and I still don't mean any disrespect when I'm saying this:

The grammar errors in the error message are not acceptable as well. It makes me to rethink, that can I really trust the product, the code, when even the error messages are full of errors and inconsistency?

BR,
Tiexin

**Comment by leonrodenburg** [comment]
@IronCore864 No problem, but opening a comment with 'I hate everything about it' on someone else's open-source library where you've never committed yourself can sound a bit harsh.

I agree about the documentation and your point about Infra-as-Code. But as this is an open-source project, you could just add the notes and examples to the documentation yourself. You will see that the maintainers are more than willing to accept your PR. Same goes for spelling mistakes in the documentation.

As for the error messages on the API side: there's not much we can do. Best thing we can do is open a support ticket or find the people that are working on the specific products. The support team and product developers are also very willing to help and fix any issues.
