### ISSUE TITLE
Fail to create alicloud_instance because of timeout

### ISSUE THREAD

**Issue by ala2208** [terraform-providers/terraform-provider-alicloud#1060]
Hi,

We fail to create alicloud_instance, because of timeout.
In terraform provider relevant link to timeout code:
https://github.com/terraform-providers/terraform-provider-alicloud/blob/ac5358e0c73b22adc8e54b67ec089968d9691356/alicloud/resource_alicloud_instance.go#L374

See full error below.

Is there an option to increase a timeout?
Please add an ability to provide timeout configuration for resources creation like here (https://www.terraform.io/docs/providers/aws/r/instance.html#timeouts)

### Error
alicloud_instance.jb: Still creating... (8m20s elapsed)
Error: Error applying plan:
1 error(s) occurred:
* alicloud_instance.jb: 1 error(s) occurred:
* alicloud_instance.jb: WaitForInstance Running got error: &alicloud.ProviderError{errorCode:"WaitForTimeout", message:"Waitting for ECS Instance Running is timeout."}

Thanks,
Ala

**Comment by xiaozhu36** [comment]
HI @ala2208 This error comes from running ecs instance timeout. Please wait some minutes and try again. Also, this provider will add `timeouts` setting in the next future and please be patient. Thanks.

**Comment by OlegGerber** [comment]
Hi @xiaozhu36,
This issue happened frequently on our landscapes, we can't always retry it.
Please provide auto-retry functionality or possibility to extend the "ECS Instance creation timeout " from the hardcoded value 8.40 min

**Comment by xiaozhu36** [comment]
HI @OlegGerber @ala2208 This issue has been fixed by 1.46.0. Please check it.

**Comment by ala2208** [comment]
Hi @xiaozhu36 
We tested the issue with terraform-provider-alicloud_v1.46.0_x4 and it the problem is reproduced.

Did you add an ability to provide timeout configuration for resources creation like here?(https://www.terraform.io/docs/providers/aws/r/instance.html#timeouts)

Error:
alicloud_instance.jb: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_instance.go:382:
timeout while waiting for state to become 'Running' (last state: 'Starting', timeout: 10m0s)

**Comment by xiaozhu36** [comment]
HI @ala2208 The  release 1.46.0 has added an ability to provide timeout configuration: https://www.terraform.io/docs/providers/alicloud/r/instance.html#timeouts. And the error showed the ecs instance still is "Starting". Did you check the instance status by web console when the error happened?

**Comment by ala2208** [comment]
Hi  @xiaozhu36,
Please provide example of "timeouts" configuration.
In what unit to configure timeout? (min, sec ...)?

Thanks,
Ala

**Comment by xiaozhu36** [comment]
HI @ala2208 The timeout configure is terraform resource timeouts and you can refer to : https://www.terraform.io/docs/configuration-0-11/resources.html#timeouts
