### ISSUE TITLE
Feature Request: Add ability to assume role in provider block

### ISSUE THREAD

**Issue by programmer04** [terraform-providers/terraform-provider-alicloud#1068]
## Introduction
Mechanism of assuming Role by one account to operate in another (cross-account access) is similar for [Alibaba](https://www.alibabacloud.com/help/doc-detail/93745.htm) and [AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html).  This feature is very useful in enterprise environments for managing multiple accounts in a secure and convenient way.
## Feature request
Terraform AWS provider supports it out of the box. Inside block `provider "aws" { ... }`, a user needs only fill `assume_role { ... }` to achieve the above scenario (please see in [docs](https://www.terraform.io/docs/providers/aws/index.html#assume-role)).
But unfortunately for Terraform Alibaba provider (please see in [docs](https://www.terraform.io/docs/providers/alicloud/index.html)), I cannot find this functionality, I would like to request for adding its.

**Comment by xiaozhu36** [comment]
HI @programmer04 This issue has been fixed by 1.46.0. Please check it.

**Comment by programmer04** [comment]
@xiaozhu36 I checked it. Everything works as expected. Thanks for collaboration.

**Comment by xiaozhu36** [comment]
@programmer04 Great! Thanks for your contribution.

**Comment by Song2017** [comment]
hey, where can I find a guideline?
