### ISSUE TITLE
Feature request: support adding ECS to kubernetes cluster

### ISSUE THREAD

**Issue by aylei** [terraform-providers/terraform-provider-alicloud#1070]
Hi there,

It seems that `alicloud_cs_kubernetes` and `alicloud_cs_managed_kubernetes` have a limitation that all the worker instances in the same AZ have to be the same type. 

In the alicloud web console, we usually add instances that has different type via the `adding instance to cluster` functionality. It will be useful if these two resources could support adding existing ECS to the kubernetes cluster.

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_cs_managed_kubernetes
- alicloud_cs_kubernetes

**Comment by xh4n3** [comment]
@aylei actually you can have three different instance types in three different az with alicloud_cs_kubernetes, we call it 3az cluster, and we are going to support 5 az as well in the future.
alicloud_cs_managed_kubernetes should support multiaz cluster by the end this month.

**Comment by xh4n3** [comment]
alicloud_cs_managed_kubernetes already support multiple availability zone now. check out the docs at https://www.terraform.io/docs/providers/alicloud/r/cs_managed_kubernetes.html
