### ISSUE TITLE
Feauture Request: Additional new VPN settings

### ISSUE THREAD

**Issue by frameworked** [terraform-providers/terraform-provider-alicloud#1084]
Alibaba Cloud introduced additional configuration options for VPN. Please add to alicloud provider. Those options are critical for PCI-DSS for example.

Terraform v0.11.13
+ provider.alicloud v1.40.0
+ provider.aws v2.7.0

Affected Resource(s)
- alicloud_vpn_connection

resource "alicloud_vpn_connection" "gateway2" {
  count               = "${var.enable_vpn}"
  name                = "tf-vco_test1"
  vpn_gateway_id      = "${alicloud_vpn_gateway.external_rds.id}"
  customer_gateway_id = "${alicloud_vpn_customer_gateway.gateway2.id}"
  local_subnet        = ["${var.vpc_cidr_block}"]
  remote_subnet       = ["${var.gateway_cidr_block}"]
  effect_immediately  = true

  ike_config = [{
    ike_auth_alg  = "sha256"
    ike_enc_alg   = "aes256"
    ike_version   = "ikev1"
    ike_mode      = "main"
    ike_lifetime  = 86400
    psk           = "${var.tunnel2_psk}"
    ike_pfs       = "group14"
    ike_remote_id = "${aws_vpn_connection.external_rds.tunnel2_address}"
    ike_local_id  = "testalice2"
  }]

  ipsec_config = [{
    ipsec_pfs      = "group14"
    ipsec_enc_alg  = "aes256"
    ipsec_auth_alg = "sha256"
    ipsec_lifetime = 8640
  }]
}

### Expected Behavior
Attributes for ike_auth_alg should accept additional values like 'sha256'. Alibaba Cloud updated their VPN service and provide more configuration options by now.

### Actual Behavior
What actually happened?

"ike_config.0.ike_auth_alg" must contain a valid string value should be in array []string{"sha1", "md5"}, got "sha256"

"ipsec_config.0.ipsec_auth_alg" must contain a valid string value should be in array []string{"sha1", "md5"}, got "sha256"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by xiaozhu36** [comment]
HI @frameworked This issue has been fixed by 1.42.0. Please check it. If the issue still exist, please reopen it.
