### ISSUE TITLE
Autoscaling so create new insatcnes if configuration changed

### ISSUE THREAD

**Issue by JanWaller** [terraform-providers/terraform-provider-alicloud#1193]
With AutoScaling support multiple security groups #1167 the ForceNew behavior of lots of parameters for autoscaling configuration was changed.

This completely breaks all our deployments. We relied on creating new scaling configurations if new images were selected!? Why is such a change not even mentioned in the changelog?

How can we force terraform to actually create new instance configurations if they change, or how to trigger new deployments, if the configuration is changed?
This no longer seems possible with the newest alibaba provider?

**Comment by TalentNing** [comment]
Since 2018-10-17, ScalingConfiguration is able to be modified, and this is the main reason why ForceNew was used before. 
I do not really understand ’We relied on creating new scaling configurations if new images were selected!?‘ ， could you explain how you deployments depends on ForceNew behavior.

**Comment by xiaozhu36** [comment]
HI @JanWaller From the latest release 1.46.0 has removed some `forcenew` tag and most parameters support modifying except for  `scaling_group_id`. You can see details in https://www.terraform.io/docs/providers/alicloud/r/ess_scaling_configuration.html.

**Comment by xiaozhu36** [comment]
Closed by no reply.
