### ISSUE TITLE
Plugin not supported Terraform v0.12.0

### ISSUE THREAD

**Issue by nobjohns** [terraform-providers/terraform-provider-alicloud#1223]
### Terraform Version
Terraform v0.12.0

### Affected Resource(s)

All resources

### Terraform Configuration Files

Not applicable

### Debug Output

https://gist.github.com/nobjohns/7dfc07760555350a2af166f43cb64b22

### Panic Output

https://gist.github.com/nobjohns/7dfc07760555350a2af166f43cb64b22

### Expected Behavior

Run "terraform init" without error

### Actual Behavior

"terraform init" end up with  error

### Steps to Reproduce
1. `terraform init`

**Comment by programmer04** [comment]
The same reported in issue #1188

**Comment by xiaozhu36** [comment]
Repeated with #1188
