### ISSUE TITLE
httpCallback parameter for alarms is missing

### ISSUE THREAD

**Issue by arafato** [terraform-providers/terraform-provider-alicloud#1228]
Hi--, 

is it possible to add a field vor specifying an httpCallback value to resource provider `resourceAlicloudCmsAlarm` ?

Thanks!

**Comment by arafato** [comment]
I've created a PR at https://github.com/terraform-providers/terraform-provider-alicloud/pull/1243.

**Comment by xiaozhu36** [comment]
HI @arafato  This issue has been fixed by 1.46.0. Please check it.
