### ISSUE TITLE
Bucket was not recreated after deletion and there was no notification that it does not exist

### ISSUE THREAD

**Issue by ala2208** [terraform-providers/terraform-provider-alicloud#1251]
Hi,

I created a **bucket**  with terraform successfully.
After deleted the **bucket** manually from OSS console.
Deployed the same terraform script once again and didn't get any notification that **bucket** does 
exist and of course it was not recreated`(Apply complete! Resources: 0 added, 0 changed, 0 destroyed.)`

`Terrafrom script:`
resource "alicloud_oss_bucket" "my_bucket"{
  bucket = "test"
  acl = "private"

  lifecycle_rule {
    id = "rule-days"
    prefix =  ""
    enabled = true
    expiration {
      days = "1"
    }
  }
}

Thanks,
Ala

**Comment by xiaozhu36** [comment]
HI @ala2208 This is a bug and it will be fixed by the next version.

**Comment by xiaozhu36** [comment]
HI @ala2208 This issue has been fixed by 1.46.0. Please check it.

**Comment by ala2208** [comment]
Hi  xiaozhu36 
After validation the issue has been fixed by 1.46.0. 

Thanks,
Ala
