### ISSUE TITLE
Bucket lifecycle_rule was not recreated after manual deletion

### ISSUE THREAD

**Issue by ala2208** [terraform-providers/terraform-provider-alicloud#1252]
Hi,

I created a bucket with **lifecycle_rule** using terraform successfully.
After deleted the **lifecycle_rule** manually from OSS console.
Deployed the same terraform script once again and didn't get any notification that **lifecycle_rule** does exist and of course it was not recreated`(Apply complete! Resources: 0 added, 0 changed, 0 destroyed.)`

Remark: If lifecycle_rule is modified manually in  OSS console and after it I run the same terraform script, the changes are applied.

`Terrafrom script:`
resource "alicloud_oss_bucket" "my_bucket"{
  bucket = "test"
  acl = "private"

  lifecycle_rule {
    id = "rule-days"
    prefix =  ""
    enabled = true
    expiration {
      days = "1"
    }
  }
}

Thanks,
Ala

**Comment by xiaozhu36** [comment]
HI @ala2208 This issue has been fixed by 1.46.0. Please check it.

**Comment by ala2208** [comment]
Hi @xiaozhu36
After validation the issue has been fixed by 1.46.0.

Thanks,
Ala
