### ISSUE TITLE
No configuration file name and line number associated with error message

### ISSUE THREAD

**Issue by allspace** [terraform-providers/terraform-provider-alicloud#1292]
Hi there,

Not sure if this has been reported, but I found that there is no file_name:line_number information associated with error message output from "terraform apply".

This is definitely a big issue when the size of configuration source code grows to big.

Thanks
Mike

**Comment by xiaozhu36** [comment]
HI @allspace I am sorry. Can you show me more details for this issue?

**Comment by allspace** [comment]
Error messages like below:
Error: resource 'alicloud_slb_acl.default' config: unknown variable referenced: 'ip_version'; define it with a 'variable' block
Error: resource 'alicloud_slb_server_group.web_slb_server_group' config: unknown resource 'alicloud_slb.web_slb' referenced in variable alicloud_slb.web_slb.id

**Comment by xiaozhu36** [comment]
HI @allspace This error came from your template and not terraform-provider-alicloud. Please define missing variable in your template and try again.

**Comment by xiaozhu36** [comment]
Closed by no reply
