### ISSUE TITLE
About alicloud_slb_rule

### ISSUE THREAD

**Issue by allspace** [terraform-providers/terraform-provider-alicloud#1297]
Hi there,

Using the console, when I edit a  domain/URL based "Forwarding rule", I can enable health check for the specified backend virtual server group.

However, this is not possible with alicloud_slb_rule, which seems to be able to attach a "forwarding rule" to an existing listener, but it does not have options to enable health check.

Is there a plan to add "health check" option to alicloud_slb_rule?

Thanks
Mike

**Comment by xiaozhu36** [comment]
HI @allspace The latest release 1.51.0 has been fixed it. Please check it.
