### ISSUE TITLE
Missing support for terraform import security group rule

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-alicloud#1308]
### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
- security group rule

### Expected Behavior
Terraform should be able to import the rule.

### Actual Behavior
Error: module.api.alicloud_security_group_rule.ingress(import id: sg-k1axxxxxxxx_ingress_tcp_443_443_0.0.0.0/0): import module.api.alicloud_security_group_rule.ingress(id: sg-k1axxxxxxxx_ingress_tcp_443_443_0.0.0.0/0): resource alicloud_security_group_rule doesn't support import

### Steps to Reproduce
1.  terraform import module.api.alicloud_security_group_rule.ingress sg-k1axxxxxxxx_ingress_tcp_443_443_0.0.0.0/0

**Comment by xiaozhu36** [comment]
HI @yokzy88 This feature has been supported  by 1.48.0. Please check it.

**Comment by dang-1** [comment]
actully example: terraform import alicloud_security_group_rule.ali_one_4 sg-bp196umbovnwfbz1d148:ingress:ICMP:-1/-1:intranet:0.0.0.0/0:Accept:1

**Comment by hunkjun** [comment]
The command is： terraform import alicloud_security_group_rule.sec-ecs-dns53 sg-xxxxxx:ingress:TCP:internet:22/22:0.0.0.0/0:Accept:1

but not successfully.
the error is ,

Error: alicloud_security_group_rule.sec-ecs-dns53 (import id: sg-xxxxxx:ingress:TCP:internet:22/22:0.0.0.0/0:Accept:1): 1 error occurred:
	* import alicloud_security_group_rule.sec-ecs-dns53 result: sg-xxxxxx:ingress:TCP:internet:22/22:0.0.0.0/0:Accept:1: import alicloud_security_group_rule.sec-ecs-dns53 (id: sg-xxxxxx:ingress:TCP:internet:22/22:0.0.0.0/0:Accept:1): Terraform detected a resource with this ID doesn't exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.

**Comment by hunkjun** [comment]
# it is ok by follow.
terraform import alicloud_security_group_rule.sec-ecs-dns53 sg-bp10xxxxxxxx:ingress:tcp:22/22:intranet:0.0.0.0/0:accept:1

Thanks a lot.
