### ISSUE TITLE
Failed to instantiate provider "alicloud" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by lifeblood** [terraform-providers/terraform-provider-alicloud#1335]
terraform plan

Error: Failed to instantiate provider "alicloud" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

$ terraform version
Terraform v0.12.3

**Comment by xiaozhu36** [comment]
HI @lifeblood At present, our provider does not support terraform 0.12, and we are working on it. Now, you can change it to 0.11 to fix this issue.

**Comment by xiaozhu36** [comment]
Duplicate with #1296  and #1188
