### ISSUE TITLE
CIDR and avalibility_zone parameter are required not optional

### ISSUE THREAD

**Issue by ausmartway** [terraform-providers/terraform-provider-alicloud#1342]
### Terraform Version
Terraform v0.11.14
+ provider.alicloud v1.48.0

### Affected Resource(s)
alicloud_vswitches

### Terraform Configuration Files
provider "alicloud" {
}

resource "alicloud_vpc" "alicloud_demo_vpc" {
  name       = "alicloud_demo_vpc"
  cidr_block = "172.16.0.0/12"
}

resource "alicloud_vswitch" "alicloud_demo_vswitch" {
  vpc_id = "${alicloud_vpc.alicloud_demo_vpc.id}"
  name="alicloud_demo_vswitch"
}

### Debug Output

https://gist.github.com/ausmartway/b3e1039b4da6d8a862cff825fa030712

### Expected Behavior
Expect CIDR and avalibility_zone to be optional, as per document.

### Actual Behavior
CIDR and avalibility_zone are required

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply

**Comment by xiaozhu36** [comment]
HI @ausmartway As per document, the CIDR and availibility_zone are required. Also this is product limitation and terraform provider can not change it.
