### ISSUE TITLE
Terraform crashed - when importing security group in alibaba cloud

### ISSUE THREAD

**Issue by sundarambalasubramaniam** [terraform-providers/terraform-provider-alicloud#1343]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.13
+ provider.alicloud v1.48.0

### Affected Resource(s)
-Security group

### Terraform Configuration Files
resource "alicloud_security_group_rule" "sg_rule_TCP2" {
 
 }

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
https://gist.github.com/sundarambalasubramaniam/a85f51e2f566dab5e842c653eedcabbd

### Expected Behavior
What should have happened?
import existing security group to TF

### Actual Behavior
What actually happened?
It crashed and gave an error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

[crash.log](https://github.com/terraform-providers/terraform-provider-alicloud/files/3333062/crash.log)

**Comment by xiaozhu36** [comment]
HI @sundarambalasubramaniam It seems like you used a invalid rule id to import resource alicloud_security_rule. You can refer to https://www.terraform.io/docs/providers/alicloud/r/security_group_rule.html#import and use the correct rule id to retry it.

**Comment by xiaozhu36** [comment]
Closed by no reply
