### ISSUE TITLE
auto_renew for ecs instance

### ISSUE THREAD

**Issue by wujiandong** [terraform-providers/terraform-provider-alicloud#1363]
Hi there,
 manual renewal is updated to automatic renewal for ecs instance, parameters do not take effect.

### Terraform Version
0.11.14

### Affected Resource(s)
alicloud_instance

### Terraform Configuration Files
```hcl
resource "alicloud_instance" "test002" { 

  availability_zone = "cn-zhangjiakou-b"
  instance_name = "test002"
  vswitch_id = "xxxx"
  internet_charge_type = "PayByTraffic"
  system_disk_size = "50"
  instance_type = "ecs.c5.large"
  instance_charge_type = "PrePaid"
  auto_renew_period = "1"
  renewal_status = "AutoRenewal"
  period_unit = "Month"
  internet_max_bandwidth_out = "100"

  security_groups = [ "xxx" ]
  image_id = "xxx"
  period = "1"
  system_disk_category = "cloud_efficiency"
}

```

### Expected Behavior
 manual renewal is updated to automatic renew

### Actual Behavior
no change, still is manual renew 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by xiaozhu36** [comment]
HI @wujiandong What is your provider version?

**Comment by wujiandong** [comment]
Hi xiaozhu36 

> HI @wujiandong I think the latest release 1.51.0 has fixed it and can you check it?

I have tested, it has been  fixed
