### ISSUE TITLE
Feature request: OSS backend can assume role for cross account access

### ISSUE THREAD

**Issue by OUCHUNYU** [terraform-providers/terraform-provider-alicloud#1385]
First of all, thanks to all of the maintainers of this project, I think you guys have been doing a really good job!
I saw this https://github.com/terraform-providers/terraform-provider-alicloud/pull/1217 was addressed not long ago. Thanks! https://github.com/terraform-providers/terraform-provider-alicloud/pull/1217 to me and my team only solved half of the problem. Currently, `oss` backend still doesn't support assuming roles across accounts. Therefore, every time somebody on the team wants to deploy something, he/she still has to ask the administrators to provide access credentials for the target account, apparently, this doesn't scale. 
Let me know if such feature is on the roadmap or not, if it is, when can we expect a rollout. 
Thank you!

**Comment by xiaozhu36** [comment]
HI @OUCHUNYU Thanks for your feedback. We are working on it and please be patient.

**Comment by OUCHUNYU** [comment]
@xiaozhu36 Awesome! Thanks!

**Comment by xiaozhu36** [comment]
Hi @OUCHUNYU This feature has been supported by PR: https://github.com/hashicorp/terraform/pull/22186. Please check it.

**Comment by OUCHUNYU** [comment]
@xiaozhu36 Thanks, will do!

**Comment by xiaozhu36** [comment]
Supported by [0.12.6](https://releases.hashicorp.com/terraform/0.12.6/)
