### ISSUE TITLE
Error in K8 provider: slb_internet_enabled = false creates public SLB

### ISSUE THREAD

**Issue by arafato** [terraform-providers/terraform-provider-alicloud#1394]
In resource_alicloud_cs_managed_kubernetes.go when `slb_internet_enabled = false` public SLB is still created. This should be fixed.

**Comment by xh4n3** [comment]
Hi @arafato ,
the slb_internet_enabled only applies to the API Server SLB.
the public slb is from k8s' ingress controller' service.

**Comment by xiaozhu36** [comment]
Closed by no issue.
