### ISSUE TITLE
Feature Request: upload ssl certificate of cdn resource

### ISSUE THREAD

**Issue by timclu** [terraform-providers/terraform-provider-alicloud#1395]
We have this feature in the deprecated resource `alicloud_cdn_domain `. 

But I found there is no way to set the SSL certificate in `alicloud_cdn_domain_new` or `alicloud_cdn_domain_config` which is important for enabling the https configuration.

Please help to support this feature. (PR #605 )

**Comment by xiaozhu36** [comment]
HI @timclu The latest release 1.52.0 has fixed it and please check it.

**Comment by timclu** [comment]
Verification is done.
This feature worked fine with 1.52.0.
I'll close this issue.
