### ISSUE TITLE
Alicloud Elastic Search Error: InvalidComponent

### ISSUE THREAD

**Issue by Marsyyh** [terraform-providers/terraform-provider-alicloud#1440]
Hi there,

I had issue with create elastic search in Alicloud hangzhou region. `terrform plan` works fine, failed on `terraform apply`

### Terraform Version
Terraform v0.12.4
+ provider.alicloud v1.52.0

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_elasticsearch_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# root.tf
module "es" {
  source = "./es"

  password = "${var.es_password}"
  private_whitelist = ["10.1.0.0/16", "10.2.0.0/16"]
  kibana_whitelist = ["10.1.0.0/16", "10.2.0.0/16", "127.0.0.1"]
  vswitch_id = "${element(split(",", module.vpc.vswitch_ids), 0)}"
}

# main.tf
resource "alicloud_elasticsearch_instance" "instance" {
  instance_charge_type = "${var.instance_charge_type}"
  data_node_amount     = "${var.data_node_amount}"
  data_node_spec       = "${var.data_node_spec}"
  data_node_disk_size  = "${var.data_node_disk_size}"
  data_node_disk_type  = "${var.data_node_disk_type}"
  vswitch_id           = "${var.vswitch_id}"
  password             = "${var.password}"
  version              = "${var.es_version}"
  description          = "${var.description}"
  zone_count           = "${var.zone_count}"
  master_node_spec     = "${var.master_node_spec}"
}

# variables.tf
variable "instance_charge_type" {
  default = "PostPaid"
}

variable "description" {
  default = "infra-ESResource"
}

variable "data_node_spec" {
  default = "elasticsearch.sn2ne.large"
}

variable "data_node_amount" {
  default = "3"
}

variable "data_node_disk_size" {
  default = "40"
}

variable "data_node_disk_type" {
  default = "cloud_ssd"
}

variable "es_version" {
  default = "6.7_with_X-Pack"
}

variable "vswitch_id" {
  default = "switch id"
}

variable "password" {
  default = ""
}

variable "private_whitelist" {
  type    = "list"
  default = ["10.1.0.0/16", "10.2.0.0/16"]
}

variable "kibana_whitelist" {
  type    = "list"
  default = ["10.1.0.0/16", "10.2.0.0/16", "127.0.0.1"]
}

variable "master_node_spec" {
  default = "elasticsearch.sn2ne.xlarge"
}

variable "zone_count" {
  default = "3"
}
```

### Debug Output
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_elasticsearch_instance.go:179: Resource alicloud_elasticsearch_instance CreateInstance Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InvalidComponent
Recommend: 
RequestId: 53EA5B7A-1E38-4315-896B-D5E80BD7EF70
Message: The parameters are invalid. Modify the parameters and try again.

  on es/main.tf line 1, in resource "alicloud_elasticsearch_instance" "instance":
   1: resource "alicloud_elasticsearch_instance" "instance" {

### Expected Behavior
ES resource been created

### Actual Behavior
Error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` it works
2. `terraform apply` error happens

**Comment by guangfanqu** [comment]
@Marsyyh 

In every zone, the data node amount must be at least two nodes.
So please change the `data_node_amount` to 6 or higher.

Thanks.

**Comment by Marsyyh** [comment]
@guangfanqu Thanks for the answer, it did work.

Is there any plan to improve the Errorcode ? It's really confused to see invalid parameters. At least it should tell me which parameter has issue.

Thanks : )

**Comment by xiaozhu36** [comment]
HI @Marsyyh Thanks for your feedback. I will push the product team to improve the Errorcode. @guangfanqu
