### ISSUE TITLE
If specified the `vswitch_id`, then error with `Resource 'alicloud_vswitch.vswitch' not found for variable 'alicloud_vswitch.vswitch.id'`

### ISSUE THREAD

**Issue by georgedriver** [terraform-providers/terraform-provider-alicloud#145]
Hi there,

If specified the `vswitch_id`, then error with `Resource 'alicloud_vswitch.vswitch' not found for variable 'alicloud_vswitch.vswitch.id'`

### Terraform Version
```bash
terraform -v
Terraform v0.11.7
```

### Affected Resource(s)
- ess-scaling

### Terraform Configuration Files
Check the `examples/ess-scaling/`

### Debug Output
```
terraform plan

Warning: alicloud_ess_scaling_group.scaling: "vswitch_id": [DEPRECATED] Field 'vswitch_id' has been deprecated from provider version 1.7.1, and new field 'vswitch_ids' can replace it.



Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.alicloud_zones.default: Refreshing state...
data.alicloud_images.ecs_image: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 2 error(s) occurred:

* alicloud_security_group.sg: 1 error(s) occurred:

* alicloud_security_group.sg: Resource 'alicloud_vpc.vpc' not found for variable 'alicloud_vpc.vpc.id'
* alicloud_ess_scaling_group.scaling: 1 error(s) occurred:

* alicloud_ess_scaling_group.scaling: Resource 'alicloud_vswitch.vswitch' not found for variable 'alicloud_vswitch.vswitch.id'
```

### Panic Output
NONE. 

### Expected Behavior
The `alicloud_vswitch.vswitch` should be created at lease once, then will be successfully used by resource 'alicloud_vswitch.vswitch' .

### Actual Behavior
Not working, see "Debug Output"

### Steps to Reproduce
1. Modify the `vswitch_id = "xxxxx"` in file `examples/ess-scaling/variables.tf`

2. `terraform init`

3. `terraform plan`

**Comment by seitosan** [comment]
Hi @georgedriver 

Have you your terraform configuration file ? 

Best regards

**Comment by xiaozhu36** [comment]
HI @georgedriver I am sorry for late reply. I have updated the example and please check it.

**Comment by xiaozhu36** [comment]
Closed with no reply.
