### ISSUE TITLE
alicloud_ess_scaling_configuration doesn't respect existing state, tries to change things when no change made

### ISSUE THREAD

**Issue by tsujp** [terraform-providers/terraform-provider-alicloud#1489]
### Terraform Version
Terraform v0.11.8
provider.alicloud v1.50.0

### Affected Resource(s)
`alicloud_ess_scaling_configuration`

### Terraform Configuration Files
Default

### Debug Output
```
  ~ module.redacted_for_privacy
      image_id:                    "m-redactedforprivacy" => "0"
      system_disk_size:            "40" => "0"
```

### Expected Behavior
It should not change `alicloud_ess_scaling_configuration` if no change has been made.

### Actual Behavior
It tries to change the state of the `alicloud_ess_scaling_configuration` by removing the image ID and setting the system disk size to 0 GB for the ESS scaling configuration when it hasn't been changed at all.

### Steps to Reproduce
1. Create an `alicloud_ess_scaling_configuration` by running `terraform apply`
2. Re-run `terraform apply` to simulate changing a completely different (independent resource) or doing nothing at all.
3. Observe that `alicloud_ess_scaling_configuration` ignores your configuration and state and tries to remove the image ID and set the system disk size to 0.

**Comment by TalentNing** [comment]
![image](https://user-images.githubusercontent.com/17722868/62435774-01725100-b770-11e9-828f-4b977d4ad96c.png)
![image](https://user-images.githubusercontent.com/17722868/62435803-16e77b00-b770-11e9-9701-f6702506ef48.png)

I can not reproduce, did I forget something?

**Comment by tsujp** [comment]
I just reran the script and it appears fine now too; they must have changed the API between the issue and now. So it seems solved now.
