### ISSUE TITLE
Alicloud create mongoDB and Redis

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [terraform-providers/terraform-provider-alicloud#150]
I saw the terraform docs https://www.terraform.io/docs/providers/alicloud/index.html, but I cannot find out the way for creating MongoDB and Redis.

Is that feature still in backlog? If yes, any ETA on making them live?

Thanks!

**Comment by xiaozhu36** [comment]
HI @LieAlbertTriAdrian I am sorry to tell you that at present, the provider does not support MongoDB and Redis resource. But we will support them in the future version, and lease be patient, thanks a lot.

**Comment by xiaozhu36** [comment]
HI @LieAlbertTriAdrian The release [1.15.0](https://releases.hashicorp.com/terraform-provider-alicloud/1.15.0/) has supported redis and memcache resource and please refer to [alicloud_kvstore_instance](https://www.terraform.io/docs/providers/alicloud/r/kvstore_instance.html).
In addition, we are working MongoDB resource. Please be patient. Thanks.

**Comment by xiaozhu36** [comment]
HI . @LieAlbertTriAdrian The release 1.36.0 has supported creating MongoDB instance. Please check it.
