### ISSUE TITLE
无法为一个域名添加多条MX记录

### ISSUE THREAD

**Issue by wangwenpei** [terraform-providers/terraform-provider-alicloud#1502]
类似于 #340 

已经升级到最新版，在第一次新增时无错误，在后续的apply操作时，就会出错

```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_dns_record.go:134: Resource 18047446607675392 UpdateDomainRecord Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: DomainRecordDuplicate
Recommend: 
RequestId: 77CBE627-7319-4FE8-A832-50542625B803
Message: The DNS record already exists.

  on domain.tf line 33, in resource "alicloud_dns_record" "mx2":
  33: resource "alicloud_dns_record" "mx2" {
```

版本：
```
terraform --version
Terraform v0.12.5
+ provider.alicloud v1.52.2
```

**Comment by Lexsss** [comment]
首先，您这边问题出在 不允许同一rr相同value的两条记录，如果您这边确认模版无问题，仅因为重复apply出现了以上报错，可以检查一下您的terraform与生成的tf.state文件是否正常关联，最近有客户因升级了provider等原因造成tf与tf.state关联异常，导致无论做任何操作都无法修改tf.state文件，进而产生这样一种情况：已创建的实例未被记录在tf.state中，再次apply后terraform基于上一版本的tf.state文件进行配置生成，会再次尝试创建未被记录的新增资源这样一种情况。体现在dns_record这个资源中则会报如您所述的错误。请检查terraform相关的配置信息，如确认配置信息无误，可以继续回复沟通。

**Comment by wangwenpei** [comment]
> 首先，您这边问题出在 不允许同一rr相同value的两条记录，如果您这边确认模版无问题，仅因为重复apply出现了以上报错，可以检查一下您的terraform与生成的tf.state文件是否正常关联，最近有客户因升级了provider等原因造成tf与tf.state关联异常，导致无论做任何操作都无法修改tf.state文件，进而产生这样一种情况：已创建的实例未被记录在tf.state中，再次apply后terraform基于上一版本的tf.state文件进行配置生成，会再次尝试创建未被记录的新增资源这样一种情况。体现在dns_record这个资源中则会报如您所述的错误。请检查terraform相关的配置信息，如确认配置信息无误，可以继续回复沟通。
看的有点晕，我直接全部清理重头来过，还是一样的问题。
```
terraform destory
rm -rf .terraform/
terraform init
rm -rf terraform.tfstate*
terraform apply
terraform apply     # <- error caused
```

```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_dns_record.go:134: Resource 18063004009509888 UpdateDomainRecord Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: DomainRecordDuplicate
Recommend: 
RequestId: EFCBBA2D-C815-457C-B36B-82908C06F9D9
Message: The DNS record already exists.

  on domain.tf line 33, in resource "alicloud_dns_record" "mx2":
  33: resource "alicloud_dns_record" "mx2" {
```

**Comment by Lexsss** [comment]
您好，首先您的第一次`terraform apply`之后是没有报错的，我们默认您的模板在首次创建资源时无异常。

现在，请您于第一次`terraform apply`过后在**模版不改动的情况下**进行一次`terraform plan`操作

下方可能会报出两种信息：
`No changes. Infrastructure is up-to-date.`：表示您的下一次apply不会进行任何操作。
`Plan: X to add, X to change, X to destroy.`：表示您的下一次apply会进行创建、修改或释放操作。

我们预期在不改动模板的情况下进行`terraform plan`操作会报`No changes.`信息，请您在这一步先进行一下确认。

**Comment by wangwenpei** [comment]
你好，按照你的这个提示我找到原因了。
MX记录末尾加了 ”.“ 看上去你们的provider做了一次过滤，在提交到服务器时把.滤掉了，但是实际上配置还是.

Terraform will perform the following actions:

  # alicloud_dns_record.mx1 will be updated in-place
  ~ resource "alicloud_dns_record" "mx1" {
        host_record = "@"
        id          = "18063003904062464"
        locked      = false
        name        = "##########"
        priority    = 5
        routing     = "default"
        status      = "ENABLE"
        ttl         = 3600
        type        = "MX"
      ~ value       = "##########" -> "#############."       #<- 问题在这里
    }

**Comment by Lexsss** [comment]
您好，关于资源`dns_record`重复apply报错的问题，我们已于`1.53.0`版本修复。您在升级 provider 之后，再次进行同样的操作将不会引发`DomainRecordDuplicate`错误。

另外，关于本产品，当您创建了一个`MX`的记录，**DNS后台会默认将`value`传入的域名统一加“.”，作为完全限定名来处理**(如原本就有“.”则会先过滤掉)，所以在您的使用过程中传入的`value`结尾是否加了“.”，理论上效果是一样的。

我们不建议您将加“.”的`value`传入，这将导致后台传回的`value`与您传入的`value`不符(因上一步中的过滤操作导致)，虽然通过 provider 的调整我们已解决了该问题，但我们依然不建议您传入结尾带“.”的`value`值。
