### ISSUE TITLE
alicloud_cs_managed_kubernetes error when specifying worker_data_disk_category

### ISSUE THREAD

**Issue by zipme** [terraform-providers/terraform-provider-alicloud#1504]
Hi there,

### Terraform Version
v0.12.1

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_cs_managed_kubernetes

### Terraform Configuration Files
```hcl
data "alicloud_zones" main {
  available_resource_creation = "VSwitch"
}

data "alicloud_instance_types" "default" {
  availability_zone = "${data.alicloud_zones.main.zones.0.id}"
  cpu_core_count    = 1
  memory_size       = 2
  is_outdated = "false"
  network_type = "Vpc"
  output_file = "./outputs/alicloud_instance_types"
}

resource "alicloud_cs_managed_kubernetes" "k8s" {
  name                      = "${var.name}"
  availability_zone         = "${data.alicloud_zones.main.zones.0.id}"
  new_nat_gateway           = true
  worker_instance_types     = ["${data.alicloud_instance_types.default.instance_types.0.id}"]
  worker_numbers            = "${var.work_numbers}"
  worker_disk_category      = "cloud_efficiency"
  worker_data_disk_category = "cloud_efficiency"

  password = "${var.k8s_password}"

  pod_cidr     = "172.20.0.0/16"
  service_cidr = "172.21.0.0/20"

  slb_internet_enabled  = true
  install_cloud_monitor = true
}
```

### Expected Behavior
k8s resources being created

### Actual Behavior
Got an error: Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:415: Resource cd285b211f94a42adbfc3c8da8ee505f6 strconv.Atoi Failed!!! [Provider ERROR]:
strconv.Atoi: parsing "": invalid syntax

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Note
I was able to create the resource without specifying `worker_data_disk_category`, I assume the error is because I didn't specify `worker_data_disk_size` since the doc says the default is 40.

When trying to destroy the resource I also get the error `Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:415: Resource cd285b211f94a42adbfc3c8da8ee505f6 strconv.Atoi Failed!!! [Provider ERROR]:
strconv.Atoi: parsing "": invalid syntax`

> When checking the console, the data work data disk are created and mounted correctly

**Comment by xh4n3** [comment]
@zipme we fixed it in version 1.53.0.
