### ISSUE TITLE
alicloud_fc_function add source_code_hash to detect code changes

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-alicloud#1530]
We need source_code_hash on the alicloud_fc_function so that terraform can detect if there is any changes in the source code.
Reference: Source_code_hash in AWS lambda:
https://www.terraform.io/docs/providers/aws/r/lambda_function.html#source_code_hash

How to replicate the issue:
1. Create terraform alicloud_fc_function with a local file system:
```
resource "alicloud_fc_function" "my_function" {
    service     = "my_service"
    name        = "my_function"
    filename    = "index.zip"
    memory_size = "512"
    timeout     = "60"
    runtime     = "python3"
    handler     = "index.handler"
}
data "archive_file" "my_zip" {
  type        = "zip"
  source_file = "index.py"
  output_path = "index.zip"
}
```
2. Create a source code index.py:
```
def handler(event, context):
    print('Hellow World')
```
3. Execute terraform apply
4. Modify the source code index.py
5. Re-execute terraform apply

Actual behaviour:
 - Terraform didn't detect any changes
Expected behaviour:
 - Terraform able to detect there is any code changes in the index.py. (Via source code hash)

**Comment by xiaozhu36** [comment]
HI @yokzy88 The alibaba cloud function compute use `crc64 algorithm` to compute the file checksum. From the release 1.59.0 has provided a new data source [alicloud_file_crc64_checksum](https://www.terraform.io/docs/configuration/functions/base64sha256.html) to support it. Please check it.

**Comment by xiaozhu36** [comment]
Closed by no reply.
