### ISSUE TITLE
Provider Version 1.54 not reading AccessKeys

### ISSUE THREAD

**Issue by acidwars** [terraform-providers/terraform-provider-alicloud#1547]
Hi there!

I recently updated to provider version 1.54 and recognized that it won't use my configured AccessKey. When I switch back to V1.53, everything works again...

### Terraform Version
```version = "~> 1.54"```

### Affected Resource(s)
- Provider V1.54

### Terraform Configuration Files
Working config
```hcl
provider "alicloud" {
  alias  = "europe"
  region = "eu-central-1"
  version = "1.53"
}
```
Not working:
```hcl
provider "alicloud" {
  alias  = "europe"
  region = "eu-central-1"
  version = "1.54"
}
```
### Debug Output
SDK.ServerError
ErrorCode: MissingParameter
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingParameter&source=PopGw
RequestId: 2BC4BAE3-AB1C-440C-9EB3-A52C840F621C
Message: The input parameter "AccessKeyId" that is mandatory for processing this request is not supplied.
2019/08/13 07:22:16 [ERROR] <root>: eval: *terraform.EvalSequence, err: [ERROR] terraform-provider-alicloud/alicloud/data_source_alicloud_vpcs.go:134: Datasource alicloud_vpcs DescribeVpcs Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: MissingParameter
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingParameter&source=PopGw
RequestId: 2BC4BAE3-AB1C-440C-9EB3-A52C840F621C
Message: The input parameter "AccessKeyId" that is mandatory for processing this request is not supplied.
2019/08/13 07:22:16 [TRACE] [walkRefresh] Exiting eval tree: data.alicloud_vpcs.china_vpc
2019/08/13 07:22:16 [TRACE] vertex "data.alicloud_vpcs.china_vpc": visit complete

### Expected Behavior
Resources should be created

### Actual Behavior
Terraform stops with the error message **"The input parameter "AccessKeyId" that is mandatory for processing this request is not supplied."**

### Steps to Reproduce
1. `terraform apply`

**Comment by YY-tomorrow** [comment]
I confirm that you have set ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY in the environment variable, just upgraded to 1.54.0, is there any other operation? Because I tried to reproduce, but did not succeed.

**Comment by YY-tomorrow** [comment]
Hi there! Is the issue about AccessKey resolved?

**Comment by acidwars** [comment]
I think this was Layer 8 Problem! It works now...
