### ISSUE TITLE
alicloud v1.52.2 An argument named "data_disks" is not expected here

### ISSUE THREAD

**Issue by mylife6585** [terraform-providers/terraform-provider-alicloud#1548]
### Terraform Version
Terraform v0.12.6
+ provider.alicloud v1.52.2

### Affected Resource(s)
- alicloud_instance

### Terraform Configuration Files
```hcl
resource "alicloud_instance" "instance_k8s14_node_6" {
  availability_zone          = "cn-hangzhou-f"
  deletion_protection        = false
  image_id                   = "m-bp19ftqc3qgsejus78gd"
  instance_charge_type       = "PrePaid"
  period_unit                = "Week"
  instance_name              = "pro_k8s14_node_6"
  host_name                  = "pro-k8s14-node-6.souban.internal"
  instance_type              = "ecs.e3.medium"
  internet_charge_type       = "PayByTraffic"
  internet_max_bandwidth_out = 0
  security_groups = [
    "sg-bp14oz5rxm1snr1vx0b1",
  ]
  spot_price_limit     = 0
  spot_strategy        = "NoSpot"
  system_disk_category = "cloud_efficiency"
  system_disk_size     = 20
  data_disks = [
    {
      name     = "disk_k8s14_node_6"
      size     = "20"
      category = "cloud_ssd"
    },
  ]
  tags = {
    "app"  = "k8s14"
    "env"  = "production"
    "role" = "node"
  }
  vswitch_id = "vsw-bp1dwhwtmk3f1te8m92lg"
}
```

### Debug Output
Error Log: An argument named "data_disks" is not expected here. Did you mean to define a
block of type "data_disks"?

alicloud v1.52.2 , ECS instance does not support data_disks argument ?

**Comment by ddaddaddda** [comment]
I guess that your terraform version maybe  equal or greater than 0.12, there are some expressions changed after 0.12, for more detail:  [https://www.terraform.io/docs/configuration/expressions.html](url),
you can rewrite data_disks like this: 
`
data_disks {
      name     = "disk1"
      size     = "20"
      category = "cloud_ssd"
}
data_disks {
      name     = "disk2"
      size     = "20"
      category = "cloud_ssd"
}
`

**Comment by mylife6585** [comment]
@ddaddaddda  tks， problem is over
