### ISSUE TITLE
Unable to get access_key_id and secret from aliyun cli config file on terraform-provider-alicloud1.54

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-alicloud#1558]
Hi there,
After updating the terraform provider into v.1.54, Terraform unable to get access_key_id and access_secret_key from aliyun cli config file.

### Terraform Version
Terraform v0.11.14
+ provider.alicloud v1.54.0

### Terraform Configuration Files
```
data "alicloud_account" "current_account" { }
provider "alicloud" {
  region    = "ap-southeast-5"
  version   = "~> 1.54"    
}
```

### Expected Result
Terraform able to read the default config file that was configured via aliyun cli, just like previous version (Tested successfully on provider.alicloud v.1.52.0
The config file usually is under ~/.aliyun/config.json

### Actual Result
data.alicloud_account.current_account: Refreshing state...

Error: Error refreshing state: 1 error occurred:
        * data.alicloud_account.current_account: 1 error occurred:
        * data.alicloud_account.current_account: data.alicloud_account.current_account: SDK.ServerError
ErrorCode: MissingAccessKeyId
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingAccessKeyId&source=PopGw
RequestId: E00935F6-03BC-441B-BB17-362B14594350
Message: AccessKeyId is mandatory for this action.

**Comment by YY-tomorrow** [comment]
Hi there,The 1.54 version uses the aliyun cli configuration file to set the profile, or configure the ALICLOUD_PROFILE in the environment variable. If the above configuration is successful, check whether the name in the config.json file is the same as the profile setting. The 1.54 version does not default to get the name as default.

**Comment by YY-tomorrow** [comment]
Hi there! Is the issue about AccessKey resolved?

**Comment by yokzy88** [comment]
Hi @YY-tomorrow ,
Sorry just replying.
Can you please explain what do you mean with the profile setting?
> the name in the config.json file is the same as the **profile setting**

For reference, here is my config.json. It's autogenerated and I don't change anything.
![Uploading image.png…]()

**Comment by yokzy88** [comment]
Ah I got what you mean now.
So I should put the new profile attribute on the alicloud provider.
```
provider "alicloud" {
  region    = "ap-southeast-5"
  version   = "~> 1.54"    
  profile = "default"
}
```
I think it would be better to update the documentation to use this provider configuration, since I believe writing access key in a terraform files is not a best practice.

Thanks a lot @YY-tomorrow

**Comment by YY-tomorrow** [comment]
Yes, that's it. We have a variety of ways to get the key, and we can choose the most suitable one.
