### ISSUE TITLE
Change the logic for STS to use region specific endpoint

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-alicloud#1603]
Hi there,
Actually, there is a reliability problem on the aliyun side, especially on the sts endpoint as you can see in the attached screenshot:
![image](https://user-images.githubusercontent.com/32846569/63753166-bb2a9080-c8dc-11e9-99ae-60accf35b717.png)

As you can see, the **sts.aliyuncs.com** is mainland china endpoint, and it is unreliable / intermittently timeout when pinged from my local laptop (I'm in Indonesia).
According to Aliyun customer service, they ask to use **sts.ap-southeast-5.aliyuncs.com** instead, which is more reliable when used from my side.

Therefore this request is to ask to change the logic for STS, which is to adjust the endpoint according to the user region (I use ap-southeast-5 in my terraform region configuration).
I believe this will also improve the Terraform performance, because as you can see the ping is also better if we use nearby region endpoint.

### Terraform Version
Terraform v0.11.14
+ provider.alicloud v1.52.1
+ provider.archive v1.2.2

### Affected Resource(s)
 - data "alicloud_account"
 - data "alicloud_regions"
 - resource "alicloud_fc_service"
 
### Terraform Configuration Files
```
data "alicloud_regions" "current_region" { current = true }
provider "alicloud" {
  region    = "ap-southeast-5"
  version   = "1.52.1"
}
```

### Expected Behavior
Terraform executed successfully

### Actual Behavior
Terraform got a timeout error
![image](https://user-images.githubusercontent.com/32846569/63753834-0c874f80-c8de-11e9-80f6-923a3eb31769.png)

### Important Factoids
 - The problem maybe cannot be replicated (unless you are also in Indonesia).
 - The problem is intermittent. Sometimes you will succeed, sometimes you will get timeout error

**Comment by xiaozhu36** [comment]
HI @yokzy88 I am sorry for late reply. This is the provider bug and it will be fixed in the nearly period. And as a workaround, you can set a endpoint `sts.ap-southeast-5.aliyuncs.com` by provider field `sts`, like the following:
```
provider "alicloud" {
  region    = "ap-southeast-5"
  version   = "1.52.1"
  endpoints = {
      sts = "sts.ap-southeast-5.aliyuncs.com"
  }
}
```

**Comment by yokzy88** [comment]
Thanks for the workaround @xiaozhu36. That's new to me.

**Comment by xiaozhu36** [comment]
HI @yokzy88 The release 1.57.2 has supported the correct endpoint. Please update and check it.

**Comment by xiaozhu36** [comment]
Closed by no reply.
