### ISSUE TITLE
alicloud_instance中的参数"internet_max_bandwidth_out"请支持更大的带宽

### ISSUE THREAD

**Issue by jijianming** [terraform-providers/terraform-provider-alicloud#1627]
internet_max_bandwidth_out - (Optional) Maximum outgoing bandwidth to the public network, measured in Mbps (Mega bit per second). Value range: [0, 100]. Default to 0 Mbps.默认只能选择100m，但是我这边在阿里云的控制台申请的时候可以选择300M，如何设置支持300M带宽？
![QQ图片20190903120233](https://user-images.githubusercontent.com/15081733/64143472-c896cc00-ce42-11e9-863f-74125839b323.png)

**Comment by GabrielZabielski** [comment]
For example, this is London (eu-west-1) region. 
![image](https://user-images.githubusercontent.com/34765951/64209587-2c4fe200-cea1-11e9-93d3-ab9c9995543d.png)

Please, don't forget about listing the correct value for each region in the terraform documentation.

**Comment by xiaozhu36** [comment]
HI  @jijianming This issue has been fixed by 1.55.4 and please check it. Please let me know if you still have any issues.

**Comment by xiaozhu36** [comment]
Closed by no rely
