### ISSUE TITLE
Can not build provider due to git.apache.org/thrift.git is unavaliable

### ISSUE THREAD

**Issue by imjoey** [terraform-providers/terraform-provider-alicloud#1659]
Hi there,

The provider could not be successfully built due to the `git.apache.org` downtime. The root cause has been described in https://github.com/hashicorp/terraform/issues/22664 and https://github.com/hashicorp/terraform/pull/22741, which also introduce several workarounds. From my point of view, the ultimate solution is to update the version of terraform this provider depends on to `v0.12.9`, which completely remove the `thrift` module from dependency graph. As the version change is probably not in the plan, so I open this for tracking the overall progress.

### Terraform Version
`Terraform v0.12.9`

### Affected Resource(s)
None.

### Steps to Reproduce
1. Prepare a fresh clean environment without any go packages installed;
2. Clone the provider and run `make build`

### Expected Behavior
Successfully built.

### Actual Behavior

Executing `make build` would generate the error outputs below:

```
......
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
fatal: unable to access 'https://git.apache.org/thrift.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.apache.org:443
......
go: error loading module requirements
make: *** [GNUmakefile:76: mac] Error 1
```

**Comment by xiaozhu36** [comment]
HI  @imjoey I am sorry for late reply. This issue seems like you download `git.apache.org/thrift.git` failed and please check your network environment.

**Comment by imjoey** [comment]
@xiaozhu36  Just now, I figured it out that `git.apache.org/thrift.git` has been redirected to `github.com/apache/thrift.git`, so everything works fine. I'll close this now. Thanks.
