### ISSUE TITLE
导入存在的eip时，错误显示无法找到相应的ID

### ISSUE THREAD

**Issue by hunkjun** [terraform-providers/terraform-provider-alicloud#1667]
## 声明
eip-nnnnnnnnnn  EIP在阿里云页面能查询到，正常使用中；

## 导入命令
terraform import -input=false  module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this eip-nnnnnnnnnn

## 显示报错
module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this: Importing from ID "eip-nnnnnnnnnn"...
module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this: Import complete!
  Imported alicloud_eip (ID: eip-nnnnnnnnnn)
module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this: Refreshing state... (ID: eip-nnnnnnnnnn)

Error: module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this (import id: eip-xxxxx): 1 error occurred:
	* import module.base-dns-hz-ali-xxxx-com.module.instance.alicloud_eip.this result: eip-nnnnnnnnnn: import module.base-dns-hz-ali-xxxx-com.instance.alicloud_eip.this (id: eip-nnnnnnnnnn): 

**Terraform detected a resource with this ID doesn't exist.** 

**Please verify the ID is correct. You cannot import non-existent**

resources using Terraform import.

**Comment by Lexsss** [comment]
请问您用的是哪个module？

**Comment by Lexsss** [comment]
hi @hunkjun ，我在本地实现了一下module的两层嵌套，最后将 eip 成功 import 到了 terraform 中

![image](https://user-images.githubusercontent.com/43914049/65830603-78951300-e2e3-11e9-9853-3c73cb1ac698.png)

现可以确定该嵌套模式实质上是没有问题的，考虑您的 eip 不存在或并未存在于 TF 当前使用账户下。如有任何疑问欢迎在这里回复。

**Comment by hunkjun** [comment]
你好，感谢回复；
确实是该账户没有读取eip的权限，已修正，谢谢支持~
