### ISSUE TITLE
Modifying alicloud_slb_rule name should not force new resource

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-alicloud#1680]
Hi there,
As in title, modifying slb rule name should not force new resource.

### Terraform Version
Terraform v0.11.14
- provider.alicloud v1.55.4

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_slb_rule

### Terraform Configuration Files
```
resource "alicloud_slb" "api" {
  name = "api-slb"
  specification = "slb.s2.small"
}
resource "alicloud_slb_server_group" "api_servers" {
    load_balancer_id = "${alicloud_slb.api.id}"
    servers = [
        {
            server_ids = [
              "i-xxxxxxxxxxxxxxxxxx",
              ]
            port = 1234
        }
    ]
}
resource "alicloud_slb_rule" "api_rule" {
  load_balancer_id = "${alicloud_slb.api.id}"
  frontend_port = "443"
  name = "public_api"      -> **modify this value**
  domain = "api.mydomain.com"
  url  = ""
  server_group_id = "${alicloud_slb_server_group.api_servers.id}"
}
```

### Expected Behavior
What should have happened?
Modifying alicloud_slb_rule description should not force to recreate the rule

### Actual Behavior
Modifying alicloud_slb_rule description force to recreate the rule
![image](https://user-images.githubusercontent.com/32846569/65616109-b4c72b80-dfe4-11e9-8dc3-3e387df8e3b2.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
 - terraform apply

**Comment by xiaozhu36** [comment]
HI @yokzy88 The latest version 1.57.1 has supported to update rule name and please check.

**Comment by xiaozhu36** [comment]
Closed by no reply
