### ISSUE TITLE
Remote backend with assume role doesn't work.

### ISSUE THREAD

**Issue by GabrielZabielski** [terraform-providers/terraform-provider-alicloud#1707]
Hi guys,

I've got a problem with assume role on the remote backend initialization. I tried to do the same action with only credentials to the backend destination account, and that's works well. 

### Terraform Version
Terraform v0.12.9
+ provider.alicloud v1.57.0

### Affected Resource(s)
- remote_backend - OSS

### Terraform Configuration Files
```hcl
terraform {
  backend "oss" {
    bucket = "random-bucket-name"
    key    = "version-1.tfstate"
    region = "ap-southeast-1"
    assume_role {
      role_arn           = "acs:ram::**2nd_account_id**:role/AccessToOSSFrom1stAccount"
      session_expiration = 999
    }
    access_key = "**1st_account**"
    secret_key = "****credentials****"
  }
}
```

### Expected Behavior
- The state should be saved in the `random-bucket-name` using assume role.

### Actual Behavior
```
[root@iZgw8conflthdkvcxzz4fwZ app]# terraform init

Initializing the backend...

Error: SDK.ServerError
ErrorCode: NoPermission
Recommend: 
RequestId: A39492BE-62A4-40C2-819F-BE6DFD3B1B5D
Message: You are not authorized to do this action. You should be authorized by RAM.
```
### Steps to Reproduce
- You need two accounts,
- 1st account with user credentials with attached `AliyunSTSAssumeRoleAccess` policy.
- 2ed account with role (in my example named `AccessToOSSFrom1stAccount`), with attached `FullAccessToOSS` policy. This role must be in `Trust relation` with 2nd account (2nd account is able to assume this role - `Trust policy`).
- Complete my example with above credentials and role
- `terraform init`

**Comment by liuxu6** [comment]
Hello, @GabrielZabielski . I had not encountered any problems.
Can you provide more auxiliary information, such as *.tf files and operation steps details? 
Those can help us find the problem and fix it more quickly.
Thanks so much for your support.

**Comment by xiaozhu36** [comment]
Hi  @GabrielZabielski Please let me know whether this issue still existed. Thanks.

**Comment by xiaozhu36** [comment]
Seem with #1708
