### ISSUE TITLE
Feature request: ecs_role_name ability for OSS remote backend 

### ISSUE THREAD

**Issue by GabrielZabielski** [terraform-providers/terraform-provider-alicloud#1708]
Hi there,

I have noticed that the `OSS remote backend` requires RAM User credentials or STS token to work correctly. It's possible to add authentication based on ECS RAM Role or `Provider`?

### References
https://github.com/terraform-providers/terraform-provider-alicloud/issues/1707

**Comment by xiaozhu36** [comment]
Hi @GabrielZabielski The terraform [PR](https://github.com/hashicorp/terraform/pulls) has supported it. Please check it.

**Comment by huczas** [comment]
So, you merged https://github.com/hashicorp/terraform/pull/22821/commits/c1ab1578a417da651081218007cd43e9cf292bf7 this change but in master version there are nothing that correspond with your changes made.

I've checked file in master and in tag v0.12.10 file backend/remote-state/oss/backend.go there is no field ecs_role_name. Can you tell with version of provider will have it?

**Comment by xiaozhu36** [comment]
HI @huczas Actually, the PR still in open and not be merged. I have no privilege to do that. Can you push terraform community?

**Comment by xiaozhu36** [comment]
Hi @GabrielZabielski @huczas The terraform version 0.12.14 has been published and it has supported this feature. Please check it.

**Comment by huczas** [comment]
I can confirm that it works now🙂
