### ISSUE TITLE
Unable to add instances to alicloud_cs_managed_kubernetes

### ISSUE THREAD

**Issue by martinkubrak** [terraform-providers/terraform-provider-alicloud#1713]
### Terraform Version
Terraform v0.12.9
+ provider.alicloud v1.57.0

### Affected Resource(s)
- alicloud_cs_managed_kubernetes

### Terraform Configuration Files
resource "alicloud_cs_managed_kubernetes" "storefront" {
  name                      = var.name
  vswitch_ids               = split(",", module.vpc.vswitch_ids)
  key_name                  = var.ssh_key_name
  pod_cidr                  = var.pod_cidr
  service_cidr              = var.service_cidr
  install_cloud_monitor     = var.install_cloud_monitor
  worker_disk_size          = var.worker_disk_size
  worker_disk_category      = var.worker_disk_category
  worker_data_disk_size     = var.worker_data_disk_size
  worker_data_disk_category = var.worker_data_disk_category
  worker_number             = var.worker_number
  worker_instance_types     = [data.alicloud_instance_types.zone_a.instance_types.0.id, data.alicloud_instance_types.zone_b.instance_types.0.id, data.alicloud_instance_types.zone_c.instance_types.0.id]
  cluster_network_type      = var.cluster_network_type

  depends_on = [
    module.vpc,
  ]
}

### Expected Behavior
A new node should be added to the cluster when worker_number increases

### Actual Behavior
terraform apply fails with:
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:368: Resource cbf5aad8d5ff44bee9ab434f9900bbb50 ScaleKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: E5E8F304-1F84-4FB2-86C2-0E508C49320A Status Code: 400 Code: MissingWorkerDataDisk Message: The parameter worker_data_disk_size not allowed empty

### Steps to Reproduce
1. Create managed k8s cluster with X amount of worker nodes.
2. Try to increase number of workers.

**Comment by Lexsss** [comment]
It's fixed in provider v1.57.1, please check it.

**Comment by martinkubrak** [comment]
@Lexsss it's working, thanks!
