### ISSUE TITLE
[Feature Request] Add missing routing rules for alicloud_dns_record

### ISSUE THREAD

**Issue by wi1dcard** [terraform-providers/terraform-provider-alicloud#1736]
### Terraform Version

None

### Affected Resource(s)

- alicloud_dns_record

According to [this](https://help.aliyun.com/document_detail/29807.html?spm=a2c4g.11186623.2.16.86ef10960KSKAG) doc, there are multiple routing rules missed in [alicloud_dns_record](https://www.terraform.io/docs/providers/alicloud/r/dns_record.html) resource, such like:

- `drpeng`
- `btvn`
- ...

It would be great if we complete the routing types list.

**Comment by xiaozhu36** [comment]
Hi @wi1dcard The release 1.58.0 has removed the limitation. Please update and try again.

**Comment by wi1dcard** [comment]
Sounds great. Thank you!
