### ISSUE TITLE
Error to compile release 1.60.0

### ISSUE THREAD

**Issue by Juan-ijuanix** [terraform-providers/terraform-provider-alicloud#1826]
I get an error when trying to compile the provider release 1.60.0 with go version go1.12.1 windows / amd64. The error is as follows.

# github.com/terraform-providers/terraform-provider-alicloud/alicloud
alicloud\data_source_alicloud_alikafka_instances.go:166:26: item.IoMax undefined (type alikafka.InstanceVO has no field or method IoMax)
alicloud\data_source_alicloud_alikafka_instances.go:167:26: item.EipMax undefined (type alikafka.InstanceVO has no field or method EipMax)
alicloud\data_source_alicloud_alikafka_instances.go:168:26: item.DiskType undefined (type alikafka.InstanceVO has no field or method DiskType)
alicloud\data_source_alicloud_alikafka_instances.go:169:26: item.DiskSize undefined (type alikafka.InstanceVO has no field or method DiskSize)
alicloud\data_source_alicloud_alikafka_instances.go:170:26: item.TopicNumLimit undefined (type alikafka.InstanceVO has no field or method TopicNumLimit)
alicloud\service_alicloud_alikafka.go:44:108: undefined: alikafka.StatusList
alicloud\service_alicloud_sag.go:320:57: undefined: smartag.DnatEntry
alicloud\service_alicloud_sag.go:360:51: undefined: smartag.Qos
alicloud\service_alicloud_sag.go:395:57: undefined: smartag.QosPolicy
alicloud\service_alicloud_sag.go:436:54: undefined: smartag.QosCar
alicloud\data_source_alicloud_alikafka_instances.go:170:26: too many errors

**Comment by xiaozhu36** [comment]
HI @Juan-ijuanix I am sorry for the issue. We have updated the sdk and fixed this issue. Please pull the latest code and have a try again.

**Comment by gonzolino** [comment]
Hi @xiaozhu36, I have the same issue as @Juan-ijuanix. Can you say in which version of the sdk exactly the fix was introduced?

**Comment by xiaozhu36** [comment]
HI  @gonzolino I think the latest codes has fixed it. Did you pull the latest codes?

**Comment by gonzolino** [comment]
Yes I pulled the latest code, so I think it should work. But this is what I get:

```
$ git pull upstream master
From https://github.com/terraform-providers/terraform-provider-alicloud
 * branch              master     -> FETCH_HEAD
Already up to date.

$ make build
==> Checking that code complies with gofmt requirements...
GOOS=darwin GOARCH=amd64 go build -o bin/terraform-provider-alicloud
# github.com/terraform-providers/terraform-provider-alicloud/alicloud
alicloud/data_source_alicloud_alikafka_instances.go:166:26: item.IoMax undefined (type alikafka.InstanceVO has no field or method IoMax)
alicloud/data_source_alicloud_alikafka_instances.go:167:26: item.EipMax undefined (type alikafka.InstanceVO has no field or method EipMax)
alicloud/data_source_alicloud_alikafka_instances.go:168:26: item.DiskType undefined (type alikafka.InstanceVO has no field or method DiskType)
alicloud/data_source_alicloud_alikafka_instances.go:169:26: item.DiskSize undefined (type alikafka.InstanceVO has no field or method DiskSize)
alicloud/data_source_alicloud_alikafka_instances.go:170:26: item.TopicNumLimit undefined (type alikafka.InstanceVO has no field or method TopicNumLimit)
alicloud/service_alicloud_alikafka.go:43:89: undefined: alikafka.StatusList
alicloud/service_alicloud_sag.go:325:57: undefined: smartag.DnatEntry
alicloud/service_alicloud_sag.go:366:51: undefined: smartag.Qos
alicloud/service_alicloud_sag.go:401:57: undefined: smartag.QosPolicy
alicloud/service_alicloud_sag.go:442:54: undefined: smartag.QosCar
alicloud/data_source_alicloud_alikafka_instances.go:170:26: too many errors
make: *** [mac] Error 2
```

**Comment by gonzolino** [comment]
Ok, after updating the `alibaba-cloud-sdk-go` dependency the error is gone:
```
diff --git a/go.mod b/go.mod
index 185b4383..52b5420a 100644
--- a/go.mod
+++ b/go.mod
@@ -2,7 +2,7 @@ module github.com/terraform-providers/terraform-provider-alicloud

 require (
        github.com/Sirupsen/logrus v0.0.0-20181010200618-458213699411 // indirect
-       github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20191010082856-e76f4c50e182
+       github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20191108070603-f326d82a7d0f
        github.com/aliyun/aliyun-datahub-sdk-go v0.0.0-20180929121038-c1c85baca7c0
        github.com/aliyun/aliyun-log-go-sdk v0.0.0-20181030123559-4e6c160e1ce5
        github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190528142024-f8d6d645dc4b
```

Maybe you have to update the go.mod file so that it picks up the new version of the sdk.

**Comment by Juan-ijuanix** [comment]
Hi @xiaozhu36 Is it PasswordInherit implamented too? I couldn´t find it in the code.
