### ISSUE TITLE
alicloud_cs_serverless_kubernetes does not output security_group_id

### ISSUE THREAD

**Issue by hcjmartin** [terraform-providers/terraform-provider-alicloud#1847]
### Expected Behavior
alicloud_cs_serverless_kubernetes cluster should be outputting security_group_id

### Actual Behavior
When trying to access as per documentation (https://www.terraform.io/docs/providers/alicloud/r/cs_serverless_kubernetes.html#security_group_id):
```
$ terraform plan

Error: Unsupported attribute

  on stack.tf line 47, in output "cluster_security_group":
  47:   value = "${alicloud_cs_serverless_kubernetes.tf_cluster_au.security_group_id}"

This object has no argument, nested block, or exported attribute named
"security_group_id".

```

**Comment by xiaozhu36** [comment]
HI @hcjmartin What your terraform version? Did you have a try using `value = "${alicloud_cs_serverless_kubernetes.tf_cluster_au.0.security_group_id}"`

**Comment by xiaozhu36** [comment]
Closed by no reply.
