### ISSUE TITLE
terraform crashes with the new provide (61)

### ISSUE THREAD

**Issue by JanWaller** [terraform-providers/terraform-provider-alicloud#1856]
With the new version of the terraform alibabab provider, we have crashes with all our scripts.
The old version still works without issues:

terraform apply
module.backend.data.terraform_remote_state.cluster: Refreshing state...
module.backend.data.terraform_remote_state.packgate: Refreshing state...
module.backend.data.terraform_remote_state.mns: Refreshing state...
module.backend.data.terraform_remote_state.initialdata: Refreshing state...
module.backend.data.terraform_remote_state.oss: Refreshing state...
module.backend.data.terraform_remote_state.internal-slb: Refreshing state...
module.backend.data.terraform_remote_state.token: Refreshing state...
module.backend.data.terraform_remote_state.vpc: Refreshing state...
module.backend.data.terraform_remote_state.milestone-slb: Refreshing state...
module.backend.data.terraform_remote_state.mongodb: Refreshing state...
module.backend.data.template_file.docker_compose: Refreshing state...

Error: rpc error: code = Unavailable desc = transport is closing

**Comment by JanWaller** [comment]
If I understand the problem correctly, it seems to be fixed with https://github.com/terraform-providers/terraform-provider-alicloud/pull/1854
Will you relase a bugfix release soon?

**Comment by xiaozhu36** [comment]
HI @JanWaller Exactly. I have fixed this issue and I will push terraform community to cut a new release asap. Please be patient.

**Comment by xiaozhu36** [comment]
HI @JanWaller The new release 1.62.0 has fixed this issue. Please update and try again.

**Comment by JanWaller** [comment]
It is fixed. Thank you.
