### ISSUE TITLE
alicloud_cs_serverless_kubernetes recreates cluster if private_zone=true

### ISSUE THREAD

**Issue by melan** [terraform-providers/terraform-provider-alicloud#1866]
### Terraform Version
terraform: 0.12.14
alicloud provider: 1.62

### Region
us-west-1

### Affected Resource(s)
- alicloud_cs_serverless_kubernetes

### Terraform Configuration Files
```hcl
resource "alicloud_cs_serverless_kubernetes" "serverless" {
  name_prefix                    = "alias-k8s-test"
  vpc_id                         = alicloud_vpc.vpc.id
  vswitch_id                     = alicloud_vswitch.vs.id
  new_nat_gateway                = false
  endpoint_public_access_enabled = false
  private_zone                   = true
  force_update                   = true
  deletion_protection            = false
  kube_config                    = "/tmp/.kube/config"
  client_cert                    = "/tmp/.kube/client-cert.pem"
  client_key                     = "/tmp/.kube/client-key.pem"
  cluster_ca_cert                = "/tmp/.kube/cluster-ca-cert.pem"
  provider                       = alicloud.argon-ali-terraform-us
}
```

### Debug Output
```
2019/11/15 00:39:08 [WARN] Provider "alicloud" produced an unexpected new value for alicloud_cs_serverless_kubernetes.serverless, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .private_zone: was cty.True, but now cty.False
```

### Expected Behavior
The cluster should remain untouched if no configuration changes happen

### Actual Behavior
The cluster is recreated every time terraform plan/apply is executed

### Steps to Reproduce
1. `terraform apply`

**Comment by xiaozhu36** [comment]
HI @melan Thanks for your feedback. @menglingwei Can you check it?

**Comment by menglingwei** [comment]
@xiaozhu36  Let me check it.

**Comment by menglingwei** [comment]
@melan What value did you set for private_zone when you created the cluster？ true or false ?

**Comment by melan** [comment]
If I used true - it triggered recreation of the cluster every time I run terraform

**Comment by menglingwei** [comment]
you can remove   force_update    or set force_update to false,and try again?

**Comment by menglingwei** [comment]
> If I used true - it triggered recreation of the cluster every time I run terraform

I know, because the DescribeClusterDetail API don't return private_zone filed.when it compare to state, they are not equal, so the cluster recreated. Let me have a test and then fixed it

**Comment by leonrodenburg** [comment]
@menglingwei I just ran into this issue as well, were you able to get a fix out? Otherwise I can submit a PR if you want.

**Comment by menglingwei** [comment]
> @menglingwei I just ran into this issue as well, were you able to get a fix out? Otherwise I can submit a PR if you want.

@leonrodenburg  you can submit a PR

**Comment by leonrodenburg** [comment]
@menglingwei Created a PR that removes `private_zone` from the read side and data source.
