### ISSUE TITLE
Add retries to OSS backend state locking

### ISSUE THREAD

**Issue by leonrodenburg** [terraform-providers/terraform-provider-alicloud#1940]
The OSS backend for Terraform state supports locking through Table Store, but if another process has acquired a lock, it immediately throws an error and exits. This is unhandy when you run Alicloud deployments in CI/CD pipelines, as the commits may follow up so fast that the previous pipeline is still running while the new one is started. The second one will crash with a state lock error.

Would it be an idea to add a retry mechanism to the PutRow call so that it will retry for a certain amount of time before exiting? We would have to add that around here: https://github.com/hashicorp/terraform/blob/4e5a18c621b71cd5488601aa2533934d00681b10/backend/remote-state/oss/client.go#L198. The row existence expectation triggers the error.
 
A lock acquire timeout will make the process a lot smoother while actively developing on an Alicloud stack. If the timeout is configurable and disabled by default there should be no breaking changes.

If necessary, I can try to whip up a PR to add this :)

**Comment by xiaozhu36** [comment]
HI  @leonrodenburg I am sorry for late reply. Thanks for your suggestion.  I think adding a retry mechanism is a good idea, but if the timeout can be self-define would be better. Would you please consider adding a timeouts field when you submit a PR?

**Comment by leonrodenburg** [comment]
@xiaozhu36 No problem! I will start on the PR and add a lock timeout field on the provider config.

**Comment by xiaozhu36** [comment]
@leonrodenburg Thanks a lot.

**Comment by leonrodenburg** [comment]
@xiaozhu36 I submitted an initial PR to the Terraform repo: https://github.com/hashicorp/terraform/pull/23801. Can you check and comment?

**Comment by leonrodenburg** [comment]
Apparently the Terraform CLI already supports the `-lock-timeout=<duration>` option, which does exactly what I need. Maybe this could be added to the docs in a more visible place. For now I'm closing the issue because TF already supports the lock timeout.
