### ISSUE TITLE
user_data in alicloud_instance should be "ForceNew"

### ISSUE THREAD

**Issue by yongzhang** [terraform-providers/terraform-provider-alicloud#1973]
Hi

I noticed that when user changing `user_data` in alicloud_instance, it will update in place not re-creating, as user_data will be executed just once when a new instance startup in common situation, so I don't think `update-in-place` is valuable, actually it makes trouble for users, because users have to manually release the instance and re-run terraform to re-create a new one to take affect updated user_data.

**Comment by xiaozhu36** [comment]
HI @yongzhang The  `user_data` can be `update-in-place` and after it is updated, the instance will reboot to make it effect.

**Comment by yongzhang** [comment]
> HI @yongzhang The `user_data` can be `update-in-place` and after it is updated, the instance will reboot to make it effect.

I think people use user_data to do one-time init tasks, most of the settings won’t take affect by reboot, that’s why “update-in-place” will make trouble.
