### ISSUE TITLE
Document and behaviour improvement for security group rule

### ISSUE THREAD

**Issue by PxSonny** [terraform-providers/terraform-provider-alicloud#2]
Hi, 

I was using Terraform 0.9.5 and just switched to 0.9.8 to double-check. The documentation is a bit misleading on the fact that either the SourceGroupId or SourceCidrIp is required. It should be mentioned.

Also if you specify any of the two it forces the creation of a new resource, which is annoying. So is there any chance a new resource would not be created when I reapply a plan I just applied and that completed perfectly fine?

Thanks,
Sonny

**Comment by xiaozhu36** [comment]
Hi @PxSonny 

Thank you for your feedback, and I'm sorry that document misled you. I will check and improve document and parameters of 'ForceNew' as soon as possible, thanks.

Regards,
Guimin

**Comment by xiaozhu36** [comment]
Hi @PxSonny 

I have improved document and added some statements about SourceGroupId or SourceCidrIp.

In addition, at present, SecurityGroupRule API does not support to modify SourceGroupId or SourceCidrIp, and SecurityGroupRule team is improving it. So, now SourceGroupId or SourceCidrIp's  change still forcibly creates a new resource. Once API has  supported it, we also will do it, thanks.

Regards,
He Guimin

**Comment by zhuzhih2017** [comment]
fxied in latest PR
