### ISSUE TITLE
Error to compile release 1.66

### ISSUE THREAD

**Issue by Junnplus** [terraform-providers/terraform-provider-alicloud#2004]
Hi there, I trying compile the provider release 1.66, but it compile error

### Debug Output
==> Checking that code complies with gofmt requirements...
GOOS=darwin GOARCH=amd64 go build -o bin/terraform-provider-alicloud
# github.com/terraform-providers/terraform-provider-alicloud/alicloud
alicloud/data_source_alicloud_alikafka_sasl_acls.go:86:13: undefined: alikafka.CreateDescribeAclsRequest
alicloud/data_source_alicloud_alikafka_sasl_acls.go:94:3: not enough arguments to return
alicloud/data_source_alicloud_alikafka_sasl_acls.go:94:24: alikafkaClient.DescribeAcls undefined (type *alikafka.Client has no field or method DescribeAcls)
alicloud/data_source_alicloud_alikafka_sasl_acls.go:98:21: undefined: alikafka.KafkaAclVO
alicloud/data_source_alicloud_alikafka_sasl_acls.go:104:23: undefined: alikafka.DescribeAclsResponse
alicloud/data_source_alicloud_alikafka_sasl_acls.go:109:83: undefined: alikafka.KafkaAclVO
alicloud/data_source_alicloud_alikafka_sasl_users.go:63:13: undefined: alikafka.CreateDescribeSaslUsersRequest
alicloud/data_source_alicloud_alikafka_sasl_users.go:96:84: undefined: alikafka.SaslUserVO
alicloud/service_alicloud_alikafka.go:174:79: undefined: alikafka.SaslUserVO
alicloud/service_alicloud_alikafka.go:221:78: undefined: alikafka.KafkaAclVO
alicloud/data_source_alicloud_alikafka_sasl_users.go:63:13: too many errors
make: *** [mac] Error 2

**Comment by xiaozhu36** [comment]
Hi @Junnplus I am sorry for late reply. The PR #2014 has fixed it. Please update and have a try again.

**Comment by Junnplus** [comment]
I pulled the latest code and try to recompile, it is working for me, thx for reply
