### ISSUE TITLE
[Feature Request] Add HealthCheckMethord to alicloud_slb_listener

### ISSUE THREAD

**Issue by yongzhang** [terraform-providers/terraform-provider-alicloud#2101]
Hi, 
Please add HealthCheckMethord to alicloud_slb_listener to support health check by "GET" or "HEAD" request, thanks.

![image](https://user-images.githubusercontent.com/15604715/72405559-57720880-3794-11ea-9f16-3e31168ea697.png)

**Comment by xiaozhu36** [comment]
HI @yongzhang I am sorry for late reply. This feature has been supported by 1.70.0:. Please check https://www.terraform.io/docs/providers/alicloud/r/slb_listener.html#health_check_method

**Comment by yongzhang** [comment]
> HI @yongzhang I am sorry for late reply. This feature has been supported by 1.70.0:. Please check https://www.terraform.io/docs/providers/alicloud/r/slb_listener.html#health_check_method

Thanks for supporting this, I tried it works.
