### ISSUE TITLE
define multiple subnets of local_subnet in alicloud_ssl_vpn_server

### ISSUE THREAD

**Issue by yongzhang** [terraform-providers/terraform-provider-alicloud#2126]
Hi, 

Looks like we can define only one CIDR to `local_subnet` in `alicloud_ssl_vpn_server`, but actually it is allowed to have multiple values in the UI, so is it possible to change `local_subnet` to `local_subnets` to allow users define multiple CIDRs here? thanks.

**Comment by xiaozhu36** [comment]
HI @yongzhang I am sorry for late reply. Currently, the `local_subnet ` supports setting multiple CIDRs by `,`. Like `local_subnet  = "10.0.1.0/24,10.0.2.0/24,10.0.3.0/24"`. Please check it.

**Comment by yongzhang** [comment]
> HI @yongzhang I am sorry for late reply. Currently, the `local_subnet ` supports setting multiple CIDRs by `,`. Like `local_subnet = "10.0.1.0/24,10.0.2.0/24,10.0.3.0/24"`. Please check it.

That’s great, thanks, I think it’s better to explain this in documents.
