### ISSUE TITLE
[alicloud_cs_serverless_kubernetes] kubeconfig output can't work 😢

### ISSUE THREAD

**Issue by caryyu** [terraform-providers/terraform-provider-alicloud#2288]
Hi there,

I tried so many times of provisioning a serverless kubernetes on alicloud, in the result, it didn't output any `kubeconfig` files in the specified folder as we expected, which I tested another API of `DescribeClusterUserKubeconfig` by using AliCloud OpenAPI Explorer, so it definitely can work well by responding a JSON result like below, thus, I suppose there must be something wrong with the resource of `alicloud_cs_serverless_kubernetes`:

```
{
	"config": "\napiVersion: v1\nclusters:\n- cluster:\n    server: https://ip:6443\n    certificate-authority-data:xxxx==\n  name: kubernetes\ncontexts:\n- context:\n    cluster: kubernetes\n    user: \"kubernetes-admin\"\n  name: kubernetes-admin-c6aaf931fbaca4d718870bb1572358098\ncurrent-context: kubernetes-admin-c6aaf931fbaca4d718870bb1572358098\nkind: Config\npreferences: {}\nusers:\n- name: \"kubernetes-admin\"\n  user:\n    client-certificate-data:xxx\n    client-key-data:xxxxx=\n"
}
```

### Terraform Version

```shell
➜ terraform -v
Terraform v0.12.23
```

### Affected Resource(s)

- alicloud_cs_serverless_kubernetes

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    alicloud = "v1.75.0"
  }
}

resource "alicloud_cs_serverless_kubernetes" "serverless" {
  name                           = var.cluster_name
  vpc_id                         = alicloud_vpc.default.id
  vswitch_id                     = alicloud_vswitch.default.id
  new_nat_gateway                = true
  endpoint_public_access_enabled = true
  private_zone                   = false
  deletion_protection            = false
  kube_config                    = "${path.module}/.kube/config"
  client_cert                    = "${path.module}/.kube/client-cert.pem"
  client_key                     = "${path.module}/.kube/client-key.pem"
  cluster_ca_cert                = "${path.module}/.kube/cluster-ca-cert.pem"
}
```

### Expected Behavior

Should output 4 files in the relative path of the workspace as HCL expressed

### Actual Behavior

Outputting Nothing at all

### Steps to Reproduce

terraform apply

### References

The API  [DescribeClusterUserKubeconfig](https://api.aliyun.com/#/?product=CS&version=2015-12-15&api=DescribeClusterUserKubeconfig&params={%22RegionId%22:%22default%22,%22ClusterId%22:%22c6aaf931fbaca4d718870bb1572358098%22}&tab=DEBUG&lang=JAVA) from [OpenAPIExplorer](https://api.aliyun.com/) can correctly return the kubeconfig information

**Comment by ringtail** [comment]
Copy. I'll check it.

**Comment by leonrodenburg** [comment]
Does the `.kube` directory already exist on disk? If not, could you create it and try again? I think I saw this behaviour before when one of the intermediate directories in the `kube_config` property path does not exist. Seeing from the code the provider does not create intermediate directories and swallows the error for `ioutil.WriteFile`.

Creation of intermediate directories would have to be added in that case.

**Comment by caryyu** [comment]
> Does the `.kube` directory already exist on disk in the module? If not, could you create it and try again? I think I saw this behaviour before when one of the intermediate directories in the `kube_config` property path does not exist. Seeing from the code the provider does not create intermediate directories and swallows the error for `ioutil.WriteFile`.
> 
> Creation of intermediate directories would have to be added in that case.

@leonrodenburg wow, that's awesome, I made it out as what you told, thanks a lot(I do think this is something should be covered in the code 😂 - by an automatic `mkdir`); but unfortunately, I encountered another same issue as what it came up with https://github.com/terraform-providers/terraform-provider-alicloud/issues/2291

If any options can enable the public API address that would be wonderful..

BTW: Close it as the original issue has been resolved.
