### ISSUE TITLE
[Bug] kubelet cannot be started by autoscaler

### ISSUE THREAD

**Issue by yagrxu** [terraform-providers/terraform-provider-alicloud#2301]
Symptom is the newly added ECS cannot be included into the K8s cluster.
problem can be found in cloud-init log in ECS 
`grep cloud-init /var/log/messages | tee /tmp/msg`
also on service
journalctl -r -u kubelet.servic

**Comment by xiaozhu36** [comment]
@ringtail Please check it.

**Comment by ringtail** [comment]
@yagrxu Pls check the NAT gateway whether the node can access internet.

**Comment by yagrxu** [comment]
@ringtail  this has been fixed in the latest terraform code https://github.com/terraform-providers/terraform-provider-alicloud/pull/2309
