### ISSUE TITLE
SSH key is not pushed to instance when updating image on Alicloud

### ISSUE THREAD

**Issue by jhagege** [terraform-providers/terraform-provider-alicloud#235]
Hi, when pushing updated image to instances, the SSH key is not updated.
Which means I need to terraform apply twice, once to "update the images", and second to "update the SSH keys", which is very inefficient and can lead to issues /long downtime when deploying.

```
Terraform will perform the following actions:

  ~ alicloud_instance.ecs_instance[0]
      image_id: "m-gw8g2nxu7rpl1i6hlqqv" => "m-gw8g2nxu7rpl3baibjxk"

  ~ alicloud_instance.ecs_instance[1]
      image_id: "m-gw8g2nxu7rpl1i6hlqqv" => "m-gw8g2nxu7rpl3baibjxk"

  ~ alicloud_instance.ecs_instance[2]
      image_id: "m-gw8g2nxu7rpl1i6hlqqv" => "m-gw8g2nxu7rpl3baibjxk"

  ~ alicloud_instance.ecs_instance[3]
      image_id: "m-gw8g2nxu7rpl1i6hlqqv" => "m-gw8g2nxu7rpl3baibjxk"

```

2nd run: 
<img width="696" alt="screen shot 2018-08-01 at 0 45 27" src="https://user-images.githubusercontent.com/7504908/43489018-3ba626d6-9524-11e8-948d-0dc141091bc9.png">

Any clue how to solve this ? 
Thanks !

**Comment by xiaozhu36** [comment]
Closed by no reply
