### ISSUE TITLE
Terraform can't add two alicloud_slb_server_group to scaling group through alicloud_ess_scalinggroup_vserver_groups

### ISSUE THREAD

**Issue by YuanQY** [terraform-providers/terraform-provider-alicloud#2505]
### Terraform Version
Terraform v0.12.17
+ provider.alicloud v1.85.0

### Affected Resource(s)
- alicloud_ess_scalinggroup_vserver_groups
- alicloud_slb_server_group
- alicloud_slb

### Terraform Configuration Files
```hcl
variable "name" {
  default = "testAccEssVserverGroupsAttachment"
}

data "alicloud_zones" "default" {
  available_disk_category     = "cloud_efficiency"
  available_resource_creation = "VSwitch"
}

resource "alicloud_vpc" "default" {
  name       = "${var.name}"
  cidr_block = "172.16.0.0/16"
}

resource "alicloud_vswitch" "default" {
  vpc_id            = "${alicloud_vpc.default.id}"
  cidr_block        = "172.16.0.0/24"
  availability_zone = "${data.alicloud_zones.default.zones.0.id}"
  name              = "${var.name}"
}

resource "alicloud_slb" "default" {
  name = "${var.name}"
  vswitch_id = "${alicloud_vswitch.default.id}"
}

resource "alicloud_slb_server_group" "default" {
  load_balancer_id = "${alicloud_slb.default.id}"
  name = "test"
}

resource "alicloud_slb_server_group" "default2" {
  load_balancer_id = "${alicloud_slb.default.id}"
  name = "test"
}

resource "alicloud_slb_listener" "default" {
  load_balancer_id = alicloud_slb.default.id
  backend_port = "8080"
  frontend_port = "80"
  protocol = "tcp"
  bandwidth = "10"
  health_check_type = "tcp"
}

resource "alicloud_ess_scaling_group" "default" {
  min_size = "2"
  max_size = "2"
  scaling_group_name = "${var.name}"
  vswitch_ids = ["${alicloud_vswitch.default.id}"]
  depends_on = ["alicloud_slb_listener.default"]
}

resource "alicloud_ess_scalinggroup_vserver_groups" "default" {
  scaling_group_id = "${alicloud_ess_scaling_group.default.id}"
  vserver_groups {
  loadbalancer_id = "${alicloud_slb.default.id}"
  vserver_attributes {
    vserver_group_id = "${alicloud_slb_server_group.default.id}"
    port = "8080"
    weight = "60"
    }
  }
}

resource "alicloud_ess_scalinggroup_vserver_groups" "default2" {
  scaling_group_id = "${alicloud_ess_scaling_group.default.id}"
  vserver_groups {
  loadbalancer_id = "${alicloud_slb.default.id}"
  vserver_attributes {
    vserver_group_id = "${alicloud_slb_server_group.default2.id}"
    port = "8080"
    weight = "50"
    }
  }
}
```

### Debug Output
https://gist.github.com/YuanQY/d3054831270c999f022759f018b64129/raw/0f9b0c6ca186c48f6b2d8fbecbf3c4f0e1f2200d/gistfile1.txt

### Panic Output
N/A

### Expected Behavior
Both alicloud_slb_server_group should add to scaling group

### Actual Behavior
Only the last alicloud_slb_server_group add to scaling group

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For No

**Comment by juhuahaoteng** [comment]
resource "alicloud_ess_scaling_group" "default" {
  min_size = "2"
  max_size = "2"
  scaling_group_name = "${var.name}"
  vswitch_ids = ["${alicloud_vswitch.default.id}"]
  depends_on = ["alicloud_slb_listener.default"]
}

没有”depends_on“ 参数

**Comment by YuanQY** [comment]
@juhuahaoteng 即使我去掉了“depends_on”, 这个问题依然在。terraform 日志 https://gist.github.com/YuanQY/d710d6548c5345f731c50d14931f022d。alicloud_ess_scalinggroup_vserver_groups只会替换掉已存在的vserver，不会添加新的vserver。这跟文档https://www.terraform.io/docs/providers/alicloud/r/ess_scalinggroup_vserver_groups.html里描述的功能不一致。
