### ISSUE TITLE
Docs: Invalid instance_network_type field for alicloud_instance

### ISSUE THREAD

**Issue by bzub** [terraform-providers/terraform-provider-alicloud#37]
https://github.com/terraform-providers/terraform-provider-alicloud/blob/master/website/docs/index.html.markdown

The example has an `instance_network_type` field for the `alicloud_instance` resource, which is not a valid field.

**Comment by bzub** [comment]
And I'm not seeing how I can specify a VPC to use, so I am stuck creating an instance with this error:
```
The specified RegionId does not support the creation of the network type ECS instance.
```

**Comment by xiaozhu36** [comment]
Hi @bzub 

I am sorry for above docs error. I have remove the error from PR  terraform-providers/terraform-provider-alicloud#11 . Please wait for official merging, thanks.

In addition, you also can refer to the latest docs from  [terraform provider docs ](http://47.95.33.19:4567/docs/providers/alicloud/), and it contains many latest function.

Regards,
He Guimin

**Comment by zhuzhih2017** [comment]
Merged
