### ISSUE TITLE
Destroying VPC

### ISSUE THREAD

**Issue by PxSonny** [terraform-providers/terraform-provider-alicloud#4]
Hi, 

I have difficulties to destroy complete infrastructure through terraform.

It seems like if I have instances still running, it still tries to destroy the vswitch first while it should stop and release the instances first. And even if I remove the instances manually and retry the destroy of the rest it says the vpc has been destroyed, but it still here in Aliyun. 

Thanks.

**Comment by xiaozhu36** [comment]
Hi @PxSonny 

Thank you for your feedback and I'm sorry for that you have happened it. Does the problem still exist?

Regards,
Guimin

**Comment by zhuzhih2017** [comment]
@PxSonny Since it's long time, I'll close this issue, if it happen again, you can reopen it. Thanks.
