### ISSUE TITLE
When apply error, How to automatically rollback?

### ISSUE THREAD

**Issue by polefishu** [terraform-providers/terraform-provider-alicloud#42]
resource "alicloud_instance" -> resource "alicloud_security_group"

when alicloud_security_group has been successful  created，but alicloud_instance return error, can terraform autmatically rollback and delete alicloud_security_group?

**Comment by bittopaz** [comment]
I don't think this is supported by terraform now..

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

I am sorry to tell you that terraform doesn't support rollback now. If alicloud_instance return error, you can run `terraform apply` again, and alicloud_security_group would not be created again, thanks a lot.

Regards,
He Guimin

**Comment by zhuzhih2017** [comment]
Hi @bittopaz 
Terraform will record the resource it already created and when error happens, you can choose to fix the error and continue the process by running the "terraform apply" again. It will create the remaining resources and don't duplicate resources you already created. If you don't want to continue the process. You can run "terraform destroy" to delete the created resources.  So what's the concern you want terraform to support the rollback?

**Comment by rquadling** [comment]
Just to help those less experienced ... when you say " you can choose to fix the error and continue the process " ... can you elaborate on the "fix" part?

Is this a correction to the terraform files (and so a new plan?), or changes to the cloud that you are attempting to modify?
