### ISSUE TITLE
Asking about the release time for Alicloud provider

### ISSUE THREAD

**Issue by siliconavengers** [terraform-providers/terraform-provider-alicloud#43]
Hi you guys,

The latest version of AliCloud provider is 0.1. And this version doesn't support few configurations such as `alicloud_key_pair_attachment` and `alicloud_oss_bucket`.

But on the master branch, I can see the codes for these configurations and I found a [documentation](http://47.95.33.19:4567/docs/providers/alicloud/r/oss_bucket.html) sharing these new changes. And all examples from this repository has updated with these configurations.

So, when you guys release the new version for AliCloud provider?

Thanks,

**Comment by xiaozhu36** [comment]
Hi @siliconavengers 

It may have some delay for synchronizing version and docs. You can use the latest version of AliCloud provider from [terraform-provider-alicloud](https://github.com/alibaba/terraform-provider/releases) and refer to the [latest docs](http://47.95.33.19:4567/docs/providers/alicloud/), thanks a lot.

Regards,
He Guimin

**Comment by oddsocksio** [comment]
so is the intention that this repository will track [terraform-provider-alicloud]?(https://github.com/alibaba/terraform-provider)

**Comment by ellerbrock** [comment]
yes, lots of good stuff!
would be nice to get it merged soon.

![bring the good shit to the community](https://media.giphy.com/media/Vti5McrcF8N2M/giphy.gif)

**Comment by zhuzhih2017** [comment]
@siliconavengers The latest version provider already release. and we already resolve the process problem and we'll release the new feature when it's available. Thanks.
