### ISSUE TITLE
Feature request: Provide support for NAS services

### ISSUE THREAD

**Issue by Marcus-James-Adams** [terraform-providers/terraform-provider-alicloud#439]
Hi
Could I request that support to create manage and destroy  NAS and services such as NAS sync are supported by the provider, please?

**Comment by xiaozhu36** [comment]
It is in our plan and please be patient. Thanks.

**Comment by Marcus-James-Adams** [comment]
Brilliant Thank you

**Comment by seitosan** [comment]
Hello,

Have you any news about the nas support ? 

regards

**Comment by seitosan** [comment]
Hello,

Have you any news about the nas support ?

regards

**Comment by xiaozhu36** [comment]
@seitosan yes, we are working on it. #807

**Comment by seitosan** [comment]
@xiaozhu36  Perfect

Do you know when it can be available ? 

regards

**Comment by xiaozhu36** [comment]
Thanks for all of patience. The new release 1.33.0 has supported two nas resource:  [access group](https://www.terraform.io/docs/providers/alicloud/r/nas_access_group.html) and [file system](https://www.terraform.io/docs/providers/alicloud/r/nas_file_system.html). More resources and datasources are coming. Please be patient.

**Comment by seitosan** [comment]
@xiaozhu36 
thanks for this news  :) I 'm impatient to test it :)

**Comment by seitosan** [comment]
@xiaozhu36  I see the nas filesystem and Acecss group support. Have you any news about the mountpoint support ? 

regards

**Comment by xiaozhu36** [comment]
HI @seitosan It has been supported by #835 . We are waiting for official publishes a new release.

**Comment by xiaozhu36** [comment]
Fixed by release 1.34.0

**Comment by seitosan** [comment]
@xiaozhu36  Perfect, thanks a lot
