### ISSUE TITLE
CS Application Deployment Error

### ISSUE THREAD

**Issue by aldojimenez** [terraform-providers/terraform-provider-alicloud#476]
Hello,

We are experiencing an issue when attempting to create a new cs_application. The terraform apply returns with an error but the cs_application does deploy successfully. The issue seems to be that the provider is passing the application name instead of the cluster name when attempting to monitor application creation status, hence returning a *Instance.Notfound* error

### Terraform Version
Terraform v0.11.10

### Affected Resource(s)
- alicloud_cs_application

### Terraform Apply Result
```
Error: Error applying plan:

1 error(s) occurred:

* module.module_name.alicloud_cs_application.main: 1 error(s) occurred:

* alicloud_cs_application.main: Waitting for container application "running" got an error: &alicloud.ProviderError{errorCode:"Instance.Notfound", message:"The specified Container Cluster my_test_cs_app is not found."}
```

Notice that the error say's my_test_cs_app when expected result would be a my_test_cs_cluster.

### Important Factoids
I believe the issue is due to a change a change from version 1.19.0 to 1.20.0. Specifically changes for  - Support provider thread safety [[GH-432](https://github.com/terraform-providers/terraform-provider-alicloud/commit/a376a64a9ac6ccc6d2d6d2be2505c094b01fdbdb#diff-f66ffd56ebd9190c25c04c3c54aa92c9R74)] which modified line 74 of file ` alicloud/service_alicloud_cs.go` changing `clusterName` to `appName`

**Comment by xiaozhu36** [comment]
HI @aldojimenez Thanks for your feedback. The PR #480 has fixed it.

**Comment by xiaozhu36** [comment]
Closed with fixed.
