### ISSUE TITLE
OSS Bucket Lifecycle Block - Missing Transitions

### ISSUE THREAD

**Issue by aldojimenez** [terraform-providers/terraform-provider-alicloud#487]
Hi,

The OSS lifecycle rule is missing the ability to transition files between different storage classes, which is supported by the API.

https://www.terraform.io/docs/providers/alicloud/r/oss_bucket.html#block-lifecycle_rule

**Comment by xiaozhu36** [comment]
HI @aldojimenez I am sorry for late reply and the release 1.62.1 has supported it. Please check it: https://www.terraform.io/docs/providers/alicloud/r/oss_bucket.html#transitions.

**Comment by xiaozhu36** [comment]
Closed by no reply
