### ISSUE TITLE
Missing support for SQL Server 2016

### ISSUE THREAD

**Issue by wojciehm** [terraform-providers/terraform-provider-alicloud#494]
Alibaba Cloud API supports SQL Server 2016 Deployment. However current provider supports up to SQL Server 2012.

https://github.com/terraform-providers/terraform-provider-alicloud/blob/a376a64a9ac6ccc6d2d6d2be2505c094b01fdbdb/alicloud/resource_alicloud_db_instance.go

Here is the list of supported DB's https://www.alibabacloud.com/help/doc-detail/26228.htm.

**Comment by xiaozhu36** [comment]
It has been fixed by #528 .

**Comment by xiaozhu36** [comment]
HI @wojciehm The new release 1.25.0 has fixed this issue. Please check.

**Comment by xiaozhu36** [comment]
Closed for no reply.
