### ISSUE TITLE
alicloud_router_interface alicloud.   ProviderError{errorCode:"Instance.Notfound", message:"The specified Router Interface ri-*** is not found."}

### ISSUE THREAD

**Issue by pingwin4ik** [terraform-providers/terraform-provider-alicloud#515]
Hi,

### Terraform Version
Terraform v0.11.10
provider "alicloud" {
  version = "1.24.0"

### Affected Resource(s)
Please list the resources as a list, for example:

resource "alicloud_router_interface" "init"

### Terraform Configuration Files
resource "alicloud_router_interface" "init" {
  opposite_region = "eu-central-1"
  router_type     = "VRouter"
  router_id       = "${alicloud_vpc.main.router_id}"
  role            = "InitiatingSide"
  specification   = "Large.2"
  name            = "perf-initia"
  description     = "perf-initiating side"
  instance_charge_type = "PrePaid"
  period = "1"
  depends_on            = ["alicloud_vpc.main"]
}

resource "alicloud_router_interface" "accept" {
  
  opposite_region = "eu-central-1"
  router_type     = "VRouter"
  router_id       = "vrt-gw8phqv0trv9zc8888l7e"
  role            = "AcceptingSide"
  specification = "Negative"
  name            = "accepting-side"
  description     = "Accepting side router interface"
  instance_charge_type = "PostPaid"
}

 #### Connection ROUTE
resource "alicloud_router_interface_connection" "init" {
  
  interface_id          = "${alicloud_router_interface.init.id}"
  opposite_interface_id = "${alicloud_router_interface.accept.id}"
  depends_on            = ["alicloud_router_interface.init","alicloud_router_interface.accept","alicloud_router_interface_connection.accept"]
}

resource "alicloud_router_interface_connection" "accept" {
  
  interface_id          = "${alicloud_router_interface.accept.id}"
  opposite_interface_id = "${alicloud_router_interface.init.id}"
  depends_on            = ["alicloud_router_interface.init"]
}

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* module.vpc.alicloud_router_interface.init: 1 error(s) occurred:

* alicloud_router_interface.init: WaitForRouterInterface Idle got error: &alicloud.ProviderError{errorCode:"Instance.Notfound", message:"**The specified Router Interface ri-gw8tofjdbfnnkv0tjlm2w is not found."}**

### Expected Behavior
created alicloud_router_interface initiating side

### Actual Behavior
The specified Router Interface ri-gw8tofjdbfnnkv0tjlm2w is not found

### Steps to Reproduce

`terraform apply`

Please look attached screenshot 
 
Route interface was created without :
 name            = "perf-initia"
 description     = "perf-initiating side"

![image](https://user-images.githubusercontent.com/25619978/48845819-34251680-eda6-11e8-86a5-c4f76f5361b4.png)

What is this  Router Interface ri-gw8tofjdbfnnkv0tjlm2w ? ( which we see in error )

When run again "terraform apply" created new router interface successful

![image](https://user-images.githubusercontent.com/25619978/48846181-1c01c700-eda7-11e8-83e3-b7fa2f809b08.png)

Issue happen 2-3 times on 10 attempts

**Comment by xiaozhu36** [comment]
HI @pingwin4ik The new release 1.25.0 has fixed this issue. Please check.

**Comment by pingwin4ik** [comment]
i checked and from time to time we have  new issue:

1 error(s) occurred:

* module.vpc.alicloud_router_interface.init: 1 error(s) occurred:

* alicloud_router_interface.init: WaitForRouterInterface Idle got error: &alicloud.ProviderError{errorCode:"WaitForTimeout", message:"Waitting for Router Interface Idle is timeout."}

**Comment by dianmuali** [comment]
Could you please tell me more about this new issue? Such as which scene will cause the problem,  thank you.

**Comment by pingwin4ik** [comment]
scenario as i mention above in topic - error was: **" The specified Router Interface ri-gw8tofjdbfnnkv0tjlm2w is not found."}**

in new release 1.25.0 i run the same code but i have another error **WaitForTimeout", message:"Waitting for Router Interface Idle is timeout."}**
and also created random route interface without :
name = "perf-initia"
description = "perf-initiating side"


 i guess timeout is 5m30s

Output:
module.vpc.alicloud_router_interface.init: Still creating... (50s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m0s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m10s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m20s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m30s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m40s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (1m50s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m0s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m10s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m20s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m30s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m40s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (2m50s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m0s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m10s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m20s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m30s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m40s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (3m50s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m0s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m10s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m20s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m30s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m40s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (4m50s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (5m0s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (5m10s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (5m20s elapsed)
module.vpc.alicloud_router_interface.init: Still creating... (5m30s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* module.vpc.alicloud_router_interface.init: 1 error(s) occurred:

* alicloud_router_interface.init: WaitForRouterInterface Idle got error: &alicloud.ProviderError{errorCode:"WaitForTimeout", message:"Waitting for Router Interface Idle is timeout."}

**Comment by dianmuali** [comment]
Hi @pingwin4ik Router Interface doesn't support "PrePaid" when region and opposite_region are the same. Please change instance_charge_type to "PostPaid".

**Comment by pingwin4ik** [comment]
> Hi @pingwin4ik Router Interface doesn't support "PrePaid" when region and opposite_region are the same. Please change instance_charge_type to "PostPaid".

Please look above- i set **instance_charge_type = "PostPaid"**

**Comment by dianmuali** [comment]
Terraform Configuration Files
resource "alicloud_router_interface" "init" {
opposite_region = "eu-central-1"
router_type = "VRouter"
router_id = "${alicloud_vpc.main.router_id}"
role = "InitiatingSide"
specification = "Large.2"
name = "perf-initia"
description = "perf-initiating side"
instance_charge_type = "PrePaid"
period = "1"
depends_on = ["alicloud_vpc.main"]
}

**Comment by dianmuali** [comment]
Hi @pingwin4ik You have changed it to "PostPaid"?

**Comment by pingwin4ik** [comment]
sorry - i set PostPaid only for AcceptingSide
I have already created via Console two Router Interfaces and it works fine (look at screenshot)
but via Terraform i have randomly issue 


![route int](https://user-images.githubusercontent.com/25619978/49501689-1e225600-f87c-11e8-8444-2cf3226a350d.png)

**Comment by xiaozhu36** [comment]
Hi @pingwin4ik Does this issue still exist?

**Comment by pingwin4ik** [comment]
no! already fixed!
