### ISSUE TITLE
Feature request: Kubernetes cluster Automatic Scaling

### ISSUE THREAD

**Issue by bilonic** [terraform-providers/terraform-provider-alicloud#532]
Hi
Is there a possibility to add creating Automatic Scaling for Kubernetes cluster?
Thanks.

**Comment by xh4n3** [comment]
for now, you have to logon to the web console, to setup ess by following the guide.
when the container service team have the ess API ready, we will enable this feature.

**Comment by xiaozhu36** [comment]
Hi @bilonic I am sorry for late reply. The latest release 1.65.0 has added a new resource: https://www.terraform.io/docs/providers/alicloud/r/cs_kubernetes_autoscaler.html to support it. Please update and check it. 
Let me know if you have any issues.

**Comment by xiaozhu36** [comment]
Closed by no reply.
