### ISSUE TITLE
Feature Request: logtail configuration and apply config to machine group

### ISSUE THREAD

**Issue by aldojimenez** [terraform-providers/terraform-provider-alicloud#553]
The provider allows you to create log projects, log stores and machine groups, but is currently missing the ability to create a logtail configuration assigned to a log store, and to map it to a machine group.

**Comment by xiaozhu36** [comment]
HI @aldojimenez This issue has been fixed by release 1.29.0. Please refer to https://www.terraform.io/docs/providers/alicloud/r/logtail_config.html
