### ISSUE TITLE
VPC deletion timeout

### ISSUE THREAD

**Issue by benjamin-bergia** [terraform-providers/terraform-provider-alicloud#58]
We had issues recently when deleting VPCs.
After creating a new VPC with terraform, we added a router interface manually using the aliyun webui.

When trying to delete the VPC on the webui, we get an error message telling us that a resource is using this VPC. Unfortunately, when trying to delete the VPC using terraform, the deletion step last few minutes and timeout without any specific error message.

PS: the router interface was using monthly billing.

**Comment by xiaozhu36** [comment]
Hi @benjamin-bergia If there are some resources in the VPC, you must delete these resource preferentially before deleting VPC. Otherwise, the VPC won't be deleted. So, you should delete router interface and other resources manually, and then delete the VPC.

Regards,
He Guimin

**Comment by benjamin-bergia** [comment]
@xiaozhu36 Yes I understand. The only issue is that in a situation where we forget to delete some resource, we don't receive any error. Just a timeout.

**Comment by xiaozhu36** [comment]
@benjamin-bergia thanks for your feedback. I will improve the Provider and output more and meaningful information when there is an error.
