### ISSUE TITLE
should get access via ~/.aliyun/config.json as well

### ISSUE THREAD

**Issue by ozbillwang** [terraform-providers/terraform-provider-alicloud#608]
### Terraform Version

```
$ terraform -v
Terraform v0.11.8
+ provider.alicloud v1.26.0
```

### Affected Resource(s)
provider "alicloud" {
  region     = "cn-hangzhou"
}

### Terraform Configuration Files
```hcl
provider "alicloud" {
  region     = "cn-hangzhou"
}

data "alicloud_instance_types" "default" {
  cpu_core_count = "1"
  memory_size    = "2"
}
```

### Debug Output
```
data.alicloud_instance_types.default: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.alicloud_instance_types.default: 1 error(s) occurred:

* data.alicloud_instance_types.default: data.alicloud_instance_types.default: Error DescribeAvailableResource: &errors.ClientError{errorCode:"SDK.CanNotResolveEndpoint", message:"Can not resolve endpoint(param = {\"Domain\":\"\",\"Product\":\"Ecs\",\"RegionId\":\"cn-hangzhou\",\"LocationProduct\":\"ecs\",\"LocationEndpointType\":\"openAPI\"}), please check the user guide\n ", originError:(*errors.ServerError)(0xc4205467e0)}
```

I knew this problem can be fixed by two ways:

1. set system environment variables `ALICLOUD_ACCESS_KEY, ALICLOUD_SECRET_KEY, ALICLOUD_REGION`

```
$ export ALICLOUD_ACCESS_KEY="anaccesskey"
$ export ALICLOUD_SECRET_KEY="asecretkey"
$ export ALICLOUD_REGION="cn-hangzhou"
$ terraform plan
```
2. provide the access keys directly via terraform variables

```
provider "alicloud" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}
```

### Expected Behavior

But my expectation is, 

3. it should read default configuration at `~/.aliyun/config.json` as well, since `aliyun-cli` sets and use it as default.

Check below codes, seems it only supports first two way currently

https://github.com/terraform-providers/terraform-provider-alicloud/blob/e57f635927a3dd981342288c0c285b966675b7b1/provider.go#L70-L99

### Actual Behavior
get access keys from `~/.aliyun/config.json` as well

**Comment by terao** [comment]
Conguraturations !
This issue solved. Yesterday applied following!
https://github.com/terraform-providers/terraform-provider-alicloud/commit/a9b0c3b895471c7ed81a744db726de8a9f7dc67e#diff-2a00105d856ee1eaa6e95280a2f19f97

**Comment by xiaozhu36** [comment]
HI everyone, the release 1.49.0 has supported this feature and please check.
