### ISSUE TITLE
Support https endpoint

### ISSUE THREAD

**Issue by ninja-at-work** [terraform-providers/terraform-provider-alicloud#609]
Hello,

Please add support for `https` connection in provider configuration. Currently, all requests to AliCloud API are sent via HTTP protocol which is not secure and contains sensitive data like access key.

Example:

```
provider "alicloud" {
   access_key = "..."
   secret_key = "..."
   region = "...region..."
   https = true
}
```

This issue is very urgent from a security perspective.

Thanks,

**Comment by ozbillwang** [comment]
May I know how you get the endpoint url? How do you know it is http, not https?

When I enable debug (`TF_LOG= DEBUG terraform apply`) I can see some extra debug logs, but these logs are not that much.

**Comment by ninja-at-work** [comment]
I did Wireshark inspections to see the requests designated to AliCloud endpoints and found that they are http based.

I would be a nice feature in terraform to include request logs if TF_LOG debug applied.

**Comment by chanind** [comment]
Wow that's scary! I tried to fix this in a PR here: #613. Does this fix the https issues you saw?

**Comment by xiaozhu36** [comment]
HI @ninja-at-work Currently, all of services has supported https and please update to release 1.27.0.

**Comment by chanind** [comment]
It looks like OTS is still using HTTP fd70bf9ade5b9479d066d238df2f0052b800a0a7. Maybe we should update the docs with a warning that using OTS resources is insecure?

**Comment by xiaozhu36** [comment]
Hi @chanind I am sorry. I am working on resolving ots supports https and it will support in the next version.

**Comment by chanind** [comment]
Ok thanks for your hard work @xiaozhu36!
