### ISSUE TITLE
 when destroy, got the error: There is no any nodes in kubernetes cluster 

### ISSUE THREAD

**Issue by ozbillwang** [terraform-providers/terraform-provider-alicloud#610]
### Terraform Version
```
$ terraform -v
Terraform v0.11.8
+ provider.alicloud v1.26.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_cs_kubernetes

### Terraform Configuration Files

I used the example `examples/kubernetes` in this repo

https://github.com/terraform-providers/terraform-provider-alicloud/blob/master/examples/kubernetes/main.tf#L52-L71

### Panic Output

```
Error: Error refreshing state: 1 error(s) occurred:

* alicloud_cs_kubernetes.k8s: 1 error(s) occurred:

* alicloud_cs_kubernetes.k8s: alicloud_cs_kubernetes.k8s: [ERROR] There is no any nodes in kubernetes cluster cd719983d556945009e0b173599832e6f.
```

### Expected Behavior
command `terraform destroy` is failed

### Actual Behavior
I have to login console, manually delete the cs kubernetes service, and re-run `terraform destroy`, it is successful

**Comment by xiaozhu36** [comment]
Hi @ozbillwang I am sorry for late reply. This is a known bug and we are working on it. If you happen it again, just terraform apply again and it can work.

**Comment by xiaozhu36** [comment]
HI @ozbillwang Does this issue still exist?

**Comment by ozbillwang** [comment]
seems there was a new release, will test it.

**Comment by xiaozhu36** [comment]
@ozbillwang If this issue has disappear, please close this issue. Thanks.

**Comment by xiaozhu36** [comment]
Closed by no reply.
