### ISSUE TITLE
Problem updating SLB with 1.26

### ISSUE THREAD

**Issue by JanWaller** [terraform-providers/terraform-provider-alicloud#626]
I have a problem updating or even accesing an exiting SLB with version 1.26
With the same scripts with 1.25 everything works.

The error is as follows:

> Error: Error refreshing state: 1 error(s) occurred:
>  
> * module.frontend_slb.alicloud_slb_listener.https: 1 error(s) occurred:
>  
> * module.frontend_slb.alicloud_slb_listener.https: alicloud_slb_listener.https: DescribeLoadBalancerHTTPSListenerAttribute got an error: &errors.ServerError{httpStatus:404, requestId:"643DB6D0-3942-4ED9-BC4B-E368BC12056F", hostId:"slb.aliyuncs.com", errorCode:"InvalidLoadBalancerId.NotFound", recommend:"", message:"The specified LoadBalancerId does not exist.", comment:""}

A manual call of DescribeLoadBalancerHTTPSListenerAttribute is also working without any issues.
The problem exists for all my SLBs.

Minimal Skript:
```
terraform {
  required_version = "~> 0.11"
}
provider "alicloud" {
  region  = "eu-central-1"
  version = "1.26"
}

resource "alicloud_slb" "milestone" {
  name                 = "w2b-dev-milestone-slb"
  internet             = true
  internet_charge_type = "PayByTraffic"
}

resource "alicloud_slb_listener" "https" {
  bandwidth        = -1
  load_balancer_id = "${alicloud_slb.milestone.id}"
  scheduler        = "wlc"
  backend_port       = "80"
  frontend_port      = "8888"
  protocol           = "https"
}

```

**Comment by JanWaller** [comment]
With 1.28 this problem still persists...

**Comment by dianmuali** [comment]
Hello @JanWaller  Did you have the successful requestId which you have at version 1.25?

**Comment by JanWaller** [comment]
I am not sure, how I would get this requestId.
Even with terraform trace logging enabled, your plugin does not really log anything it does...
If you compare this to the aws plugins, that log every server call with all parameters, it is not easy to get to know what happens in your plugin.

ActionTrail also has no entries, because nothing gets changed (as you can see above, the error happens during refresh state).

**Comment by dianmuali** [comment]
Yao have said that with the same scripts with 1.25 everything works. Could you please change the version to 1.25 and run this scripts? I think the scripts won't work with your access key even at version 1.25

**Comment by JanWaller** [comment]
I have done so many times. But just for you, with the output as "proof":
alicloud_slb.milestone: Refreshing state... (ID: lb-ge1pp1dnxqyzuxvhyinrm)
data.terraform_remote_state.vpc: Refreshing state...
alicloud_slb_acl.milestone: Refreshing state... (ID: acl-ge1979a12j5ffkvafl8at)
data.terraform_remote_state.cert: Refreshing state...
alicloud_slb_listener.https: Refreshing state... (ID: lb-ge1pp1dnxqyzuxvhyinrm:8888)
alicloud_dns_record.milestone: Refreshing state... (ID: 4141079019389952)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

**Comment by dianmuali** [comment]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/43235153/51361812-2ffa4880-1b0c-11e9-89d1-39a8c0e2da98.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/43235153/51361826-3688c000-1b0c-11e9-9fe2-4c172b20aecb.png">

**Comment by dianmuali** [comment]
The request which DescribeLoadBalancerHTTPSListenerAttribute got an error is because
 the RegionId is wrong

**Comment by JanWaller** [comment]
Ok, good find.
But what causes this?
I only change the version number of the terraform plugin.
Everything else stays exactly the same.

**Comment by JanWaller** [comment]
Fixed with newer versions
