### ISSUE TITLE
Error: alicloud_key_pairs.prod_ops: Provider doesn't support resource: alicloud_key_pairs

### ISSUE THREAD

**Issue by henry-zhang** [terraform-providers/terraform-provider-alicloud#63]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.1
+ provider.alicloud v0.1.0

### guide
I check the documents here:
http://47.95.33.19:4567/docs/providers/alicloud/d/instance_types.html

###issue
Error: alicloud_key_pairs.prod_ops: Provider doesn't support resource: alicloud_key_pairs

**Comment by bittopaz** [comment]
The new version is not released yet. 

You might want to use this one: https://github.com/alibaba/terraform-provider

**Comment by henry-zhang** [comment]
I download v1.3.3 https://github.com/alibaba/terraform-provider/releases and just put to 

➜  bin ll
total 124M
-rwxr-xr-x 1 root root  9.9M Oct 26 02:35 go
-rwxr-xr-x 1 root root   15M Oct 26 02:40 godoc
-rwxr-xr-x 1 root root  3.2M Oct 26 02:34 gofmt
-rwxrwxrwx 1 root root  3.3M Dec 20 13:45 gox
-rwxrwxrwx 1 root root  5.8M Dec 20 13:41 stringer
-rwxrwxrwx 1 root root   57M Dec 20 13:39 terraform
-rwxr-xr-x 1  501 staff  30M Dec 14 09:01 **terraform-provider-alicloud**
➜
It looks still lack that feature ?

**Comment by henry-zhang** [comment]
I also tried to build the target bin from local

go get ./...
glide up
sudo -E "PATH=$PATH" make all
cd bin
tar xvf terraform-provider-alicloud_linux-amd64.tgz -C /opt/go/bin/

Is there anything wrong with my operation ?

**Comment by henry-zhang** [comment]
after remove .terraform ,then tf init ,it works. Thanks!

**Comment by xiaozhu36** [comment]
Hi @henry-zhang We have submitted alicloud_key_pairs to terraform official repository and wait official to release new version. Please be patient and use terraform-provider-alicloud temporarily, thanks.

@bittopaz Thanks a lot.

Regards,
He Guimin

**Comment by henry-zhang** [comment]
cool!
