### ISSUE TITLE
data_source_alicloud_zones KVStore filter fails - COMMODITY.INVALID_COMPONENT

### ISSUE THREAD

**Issue by so0k** [terraform-providers/terraform-provider-alicloud#634]
### Terraform Version
Terraform v0.11.8
+ provider.alicloud v1.26.0

### Affected Resource(s)

- data "alicloud_zones"

### Terraform Configuration Files
```hcl
provider "alicloud" {
  version    = "~> 1.26"
  region     = "ap-southeast-1"
}

data "alicloud_zones" "kvstore" {
  available_resource_creation = "KVStore"
}

resource "alicloud_vswitch" "redis" {
  availability_zone = "${data.alicloud_zones.kvstore.zones.0.id}"
  name              = "${format("%s-%s", module.redis_label.id, lookup(data.alicloud_zones.kvstore.zones[0],"id"))}"
  cidr_block        = "${cidrsubnet(data.terraform_remote_state.main.vpc_cidr,8,2)}"
  vpc_id            = "${data.terraform_remote_state.main.vpc_id}"
}

resource "alicloud_kvstore_instance" "redis" {
  instance_class = "redis.master.small.default"
  instance_charge_type = "PostPaid"
  instance_type  = "Redis"                         
  engine_version = "2.8"
  instance_name  = "myredis"
  password       = "Passw0rd"
  security_ips   = ["${data.terraform_remote_state.main.vpc_cidr}"]
}
```

### Debug Output

```
* alicloud_kvstore_instance.redis: Error creating Alicloud db instance: &errors.ServerError{httpStatus:400, requestId:"5844FA44-ED47-475F-890E-364C27559E31", hostId:"r-kvstore.aliyuncs.com", errorCode:"COMMODITY.INVALID_COMPONENT", recommend:"", message:"Component choosed is not valid, please re choose it again.", comment:""}
```

### Expected Behavior

Zone should be filtered down to `ap-southeast-1b` as only zones `b` and `c` are available in the console for PayAsYouGo standard package, Master-Slave 2.8 redis clusters

### Actual Behavior

Zone `ap-southeast-1a` was used, causing this confusing, hardcoding `ap-southeast-1b` fixed the isssue

### Steps to Reproduce

1. `terraform apply`

**Comment by so0k** [comment]
Seems the data source only uses the KVStore client to filter down to supported regions and then selects any zone which has `MULTI_IZ_SYMBOL` ... which seems invalid?

https://sourcegraph.com/github.com/terraform-providers/terraform-provider-alicloud/-/blob/alicloud/data_source_alicloud_zones.go#L159

**Comment by so0k** [comment]
is this an AliCloud API issue?

**Comment by so0k** [comment]
API response still the same, any ETA so I can remove the hardcoded zone?

**Comment by xiaozhu36** [comment]
HI @so0k At present, we have supported new data source [alicloud_kvstore_instances_classes](https://www.terraform.io/docs/providers/alicloud/d/kvstore_instance_classes.html) and [alicloud_kvstore_instances_engines](https://www.terraform.io/docs/providers/alicloud/d/kvstore_instance_engines.html). Hope it can help you.

**Comment by xiaozhu36** [comment]
HI @so0k Excepted above new data source, you can also use the API DescribeAvailableResource 
 https://help.aliyun.com/document_detail/120580.html  to retrieve the available instance classes by setting zoneId and RegionId.  Please let me you have other issues.

**Comment by xiaozhu36** [comment]
Closed by no reply.
