### ISSUE TITLE
alicloud_dns_record -  ttl  value less than the minimum assigned successfully

### ISSUE THREAD

**Issue by ala2208** [terraform-providers/terraform-provider-alicloud#640]
Hi,

I created alicloud_dns_record with  ttl=300 (which is less than minimum) **successfully**.
Once I ran "terraform apply" again on scripts with no changes, terraform recognized a change and print:
          Terraform will perform the following actions:
           ~ alicloud_dns_record.dns-jumpbox
             ttl: "600" => "300"

If I choose to apply the change, an exception is thrown 
alicloud_dns_record.dns-jumpbox: UpdateDomainRecord got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"3F219C8A-5C08-498D-9F4D-11EBC267728C"}, HostId:"alidns.aliyuncs.com", Code:"QuotaExceeded.TTL", Message:"The TTL value is less than the minimum value allowed."}, StatusCode:400}

Example for alicloud_dns_record:
resource "alicloud_dns_record" "dns-jumpbox" {
  count    = 1
  name    = "*****"
  host_record = "****"
  type     = "A"
  value    = "*****"
  ttl         = 300
}

Pls. advise!

**Comment by xiaozhu36** [comment]
HI @ala2208 Your web hosting is a free version and its record's ttl minimum is 600 seconds. If you want to make it smaller, you need to upgrade your web hosting. Please check it.

**Comment by xiaozhu36** [comment]
Closed by no response.
