### ISSUE TITLE
resource `alicloud_cdn_domain` not support back-to-origin configuration

### ISSUE THREAD

**Issue by kelly-apollo** [terraform-providers/terraform-provider-alicloud#645]
### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
I have read the [document](https://www.terraform.io/docs/providers/alicloud/r/cdn_domain.html) but found nothing related.

The back to resource feature is not enabled by default.

![image](https://user-images.githubusercontent.com/4319332/50977054-b520a480-14f1-11e9-9078-8848fd821a92.png)

**Comment by xiaozhu36** [comment]
HI @kelly-apollo The release 1.34.0 provides two new resource [alicloud_cdn_domain_new](https://www.terraform.io/docs/providers/alicloud/r/cdn_domain_new.html) and [alicloud_cdn_domain_config](https://www.terraform.io/docs/providers/alicloud/r/cdn_domain_config.html). These are based on CDN's new version OpenAPI. I think these can help you. Please check it.

**Comment by xiaozhu36** [comment]
Closed by no reply.

**Comment by nikitinay** [comment]
Hello. 
I double checked links, that you provided, but haven't found exact variables, which I should apply for manage these resources.
https://www.terraform.io/docs/providers/alicloud/r/cdn_domain_new.html
https://www.terraform.io/docs/providers/alicloud/r/cdn_domain_config.html

Kindly ask you to provide options whichi can use for manage "Back-to-origin Configurations:
Thank you!
