### ISSUE TITLE
Feature Request: more CDN HTTPS configuration 

### ISSUE THREAD

**Issue by kelly-apollo** [terraform-providers/terraform-provider-alicloud#647]
Hi there,

I have read the [latest document](https://www.terraform.io/docs/providers/alicloud/r/cdn_domain.html) and related PR #605 , I found some HTTPS configuration for resource `alicloud_cdn_domain` are still missing.

IMHO, some configures are important, including
* support force HTTPS
* support Alicloud hosted certificate
* support HTTP/2

Thanks

**Comment by xiaozhu36** [comment]
Fixed by release 1.28.0.
