### ISSUE TITLE
Feature Request: alicloud_ssl_vpn_server - make "local_subnet" a list

### ISSUE THREAD

**Issue by martinkubrak** [terraform-providers/terraform-provider-alicloud#662]
Hi,

Can "local_subnet" argument for "alicloud_ssl_vpn_server" resource be a list so multiple subnets can be added?

Thanks

**Comment by xiaozhu36** [comment]
Hi @martinkubrak at present, you can setting multiple subnets by a string joined with `,` as a workaround. In the next version, we will change it to a list.

**Comment by martinkubrak** [comment]
@xiaozhu36 I'm not sure string will work due to [ValidateFunc](https://github.com/terraform-providers/terraform-provider-alicloud/blob/bf3d67854b918b71bd9e0e0acd9c97dcc487507a/alicloud/resource_alicloud_ssl_vpn_server.go#L42)

**Comment by xiaozhu36** [comment]
HI @martinkubrak Thanks for your feedback and It will be fixed by the next version.

**Comment by xiaozhu36** [comment]
Fixed by the release 1.33.0
