### ISSUE TITLE
Feature Request: support ECS Starter Package instance

### ISSUE THREAD

**Issue by humiaozuzu** [terraform-providers/terraform-provider-alicloud#664]
Hi, Could you add support for starter packages which is similar to AWS Lightsail.
https://www.alibabacloud.com/starter-packages/general

Thank you

**Comment by nightmeng** [comment]
@humiaozuzu The link you applied is a promotion and we will stop this promotion soon. 
You can try the simple application server:
https://www.alibabacloud.com/product/swas
We will support the simple application server in future.

**Comment by xiaozhu36** [comment]
Closed by no response.
