### ISSUE TITLE
alicloud_key_pair.ssh_key resource long release time (   ErrorCode: KeyPair.AlreadyExist)

### ISSUE THREAD

**Issue by OlegGerber** [terraform-providers/terraform-provider-alicloud#694]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
alicloud_key_pair.ssh_key

### Expected Behavior
The alicloud_key_pair.ssh_key should be imidiatly deleted and by terraform destroy.

### Actual Behavior
Despite the fact that we get success result from the terraform destroy command, the  alicloud_key_pair.ssh_key resource can't be recreated for a hour with error:

   alicloud_key_pair.ssh_key: Error Import KeyPair: SDK.ServerError
   ErrorCode: KeyPair.AlreadyExist

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? 
 Running cloud foundry

**Comment by nightmeng** [comment]
@OlegGerber I write a simple main.tf:
```
resource "alicloud_key_pair" "ssh_key" {
    key_name = "mytest"
}
```
and run "terraform apply" and "terraform destroy" some times, but I can't get the same error.
Can you paste your template file here for test? Thank you!

**Comment by OlegGerber** [comment]
Hi @nightmeng ,
Our template is the following and issue reproducing frequently.
resource "alicloud_key_pair" "ssh_key" {
  public_key = "xxx"
  key_name = "jumpbox-ssh-key-landscape_name}"
}

**Comment by xiaozhu36** [comment]
HI  @OlegGerber This is product's issue and it has been fixed now. If it still exists, please reopen it.
