### ISSUE TITLE
could not get all domain name

### ISSUE THREAD

**Issue by x-hezhang** [terraform-providers/terraform-provider-alicloud#702]
### Terraform Version
Terraform v0.11.10
+ provider.alicloud v1.29.0

### Affected Resource(s)
- data.alicloud_dns_domains

### Terraform Configuration Files
```hcl
data "alicloud_dns_domains" "all_domains" {
    domain_name_regex = ".*"
    output_file = "domains.txt"
}

output "all_domains" {
    value = ["${data.alicloud_dns_domains.all_domains.domains.*.domain_name}"]
}
```

### Debug Output
the output as follow:

all_domains = [
    3
]

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
I want to get all domain name, not the number of domain name.

### Actual Behavior
get the number of domain name

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by xiaozhu36** [comment]
HI @x-hezhang Can you have a try based on the following:
```
data "alicloud_dns_domains" "all_domains" {
    domain_name_regex = ".*"
    output_file = "domains.txt"
}

output "all_domains" {
    value = ["${data.alicloud_dns_domains.all_domains.domains}"]
}
```

**Comment by xiaozhu36** [comment]
Closed by no reply
