### ISSUE TITLE
Support for NAT GW as next hop in route entry

### ISSUE THREAD

**Issue by ninja-at-work** [terraform-providers/terraform-provider-alicloud#706]
Hello,

According to the [terraform documentation](https://www.terraform.io/docs/providers/alicloud/r/route_entry.html) for alicloud_route_entry the following types of next hop are supported:

- Instance (Default): Route the traffic destined for the destination CIDR block to an ECS instance in the VPC.
- RouterInterface: Route the traffic destined for the destination CIDR block to a router interface.
- VpnGateway: Route the traffic destined for the destination CIDR block to a VPN Gateway.
- HaVip: Route the traffic destined for the destination CIDR block to an HAVIP.
- NetworkInterface: Route the traffic destined for the destination CIDR block to an NetworkInterface.

The **NAT gateway** next hop type is missing here. The route can be created using portal UI, but such functionality is missing in terraform.

Thanks

**Comment by xiaozhu36** [comment]
HI . @ninja-at-work Thanks for your feedback. It will be supported in the next version. Please be patient.

**Comment by xiaozhu36** [comment]
HI @ninja-at-work This issue has been fixed by #713 . Please check.

**Comment by xiaozhu36** [comment]
Fixed by 1.30.0
