### ISSUE TITLE
issue with creating DNS record from Frankfurt region

### ISSUE THREAD

**Issue by semionshvarts** [terraform-providers/terraform-provider-alicloud#759]
Hi there,

Hi,

We have an issue with terraform on dns record creation. We get below error from time to time when we are using terraform from Frankfurt region:
 [1m [31mError:  [0m [0m [1mError applying plan:
1 error(s) occurred:
* alicloud_dns_record.aaaa_appsdomain: 1 error(s) occurred:
* alicloud_dns_record.aaaa_appsdomain: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://alidns.aliyuncs.com?AccessKeyId=LTAIrsEQPnb5KTtj&Action=DescribeDomainRecordInfo&Format=JSON&RecordId=17102136622414848&SignatureMethod=HMAC-SHA1&SignatureNonce=vYDhvGXheJB4OUORyd1vqai7NlOlaYc5&SignatureVersion=1.0&Timestamp=2019-02-10T10%3A01%3A14Z&Version=2015-01-09&Signature=nD4NyRCt%2FkX8cVNx5LSu6xVBS9M%3D: net/http: TLS handshake timeout

As the alidns.aliyuncs.com  endpoint is located in China it seems that sometimes it is not reachable from regions outside China. if it is not reachable terraform will fail the operation and we will have to retry it again. retrying is not trivial for us manually as we execute the terraform creation scripts via automations.

Thanks,
Semion

### Terraform Version
1.27.0

### Affected Resource(s)
alicloud_dns_record

### Debug Output
 [1m [31mError:  [0m [0m [1mError applying plan:
1 error(s) occurred:
* alicloud_dns_record.aaaa_appsdomain: 1 error(s) occurred:
* alicloud_dns_record.aaaa_appsdomain: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://alidns.aliyuncs.com?AccessKeyId=LTAIrsEQPnb5KTtj&Action=DescribeDomainRecordInfo&Format=JSON&RecordId=17102136622414848&SignatureMethod=HMAC-SHA1&SignatureNonce=vYDhvGXheJB4OUORyd1vqai7NlOlaYc5&SignatureVersion=1.0&Timestamp=2019-02-10T10%3A01%3A14Z&Version=2015-01-09&Signature=nD4NyRCt%2FkX8cVNx5LSu6xVBS9M%3D: net/http: TLS handshake timeout

### Expected Behavior
DNS record should be created.

### Actual Behavior
From time to time error TLS handshake timeout

### Steps to Reproduce
create DNS record from Frankfurt region with terraform

**Comment by xiaozhu36** [comment]
HI @semionshvarts I known this issue and this comes from bad network environment.  Currently you can try again to resolved. We are working on resolving it by the following two ways: 1. enforce our gateway ability to meet bad network ; 2. In the next provider version, dns resource will use our official go sdk and it will retry several times automatically when this issue happened. Please be patient.

**Comment by xiaozhu36** [comment]
HI @semionshvarts This issue has been fixed by 1.31.0. Please update and try again.

**Comment by xiaozhu36** [comment]
Closed by no reply
