### ISSUE TITLE
alicloud_vpc.vpc_name.route_table_id returns custom route table id, but not the default one

### ISSUE THREAD

**Issue by ala2208** [terraform-providers/terraform-provider-alicloud#777]
Hi,

alicloud_vpc.vpc_name.route_table_id returns custom route table id once a custom route table exists.
When custom table does not exist, we get default table id.
We run in Shanghai region.

Pls. assist
Ala

**Comment by xiaozhu36** [comment]
Hi @ala2208 I am sorry. I can not know your problem. Do you want to let alicloud_vpc.vpc_name.route_table_id returns all of router tables?

**Comment by ala2208** [comment]
Hi @xiaozhu36,
I expect alicloud_vpc.vpc_name.route_table_id to return a default table id always no if I have custom table or not.

**Comment by dianmuali** [comment]
Hi @ala2208 
Our code will return the router entry numbered first in the router table.

**Comment by dianmuali** [comment]
Could you please show the complete execution information? thank you.

**Comment by dianmuali** [comment]
It is best to provide the tf file for execution.

**Comment by ala2208** [comment]
Hi,

After running twice an example code from below "ali_vpc_default_route_table_id" and "ali_custom_route_table_id" will get the same values.

Code example: 

resource "alicloud_vpc" "route-table-id" {
  name       = "fix-route-table-id"
  description = "VPC fix-route-table-id"
  cidr_block = "10.0.0.0/8"
}
resource "alicloud_route_table" "ga_custom_table" {
  vpc_id = "${alicloud_vpc.route-table-id.id}"
  name = "ga-instance-route-table"
  description = "Dedicated route table for the GA VPC"
}
output "ali_vpc_default_route_table_id" {
  value = "${alicloud_vpc.route-table-id.route_table_id}"
}
output "ali_custom_route_table_id" {
  value = "${alicloud_route_table.ga_custom_table.id}"
}

Thanks,
Ala

**Comment by ala2208** [comment]
Hi dianmuali,

The issue is about the default and custom route table ids, but not about router entry as 
you mentioned above: "Our code will return the router entry numbered first in the router table."

**Comment by xiaozhu36** [comment]
HI @ala2208 It has been fixed by #799 . Please check it.

**Comment by ala2208** [comment]
Hi,

I validated the fix. It's o.k.

Thank You!
Ala
