### ISSUE TITLE
alicloud_disk_attachment.device_name does not return correct device_name

### ISSUE THREAD

**Issue by cloudyday** [terraform-providers/terraform-provider-alicloud#781]
Hi there,

after attaching a disk using `alicloud_disk_attachment`, I want to obtain the device_name of the disk on the VM using the `device_name` attribute. The attribute does not return the correct name.

### Terraform Version
Terraform v0.11.7
+ provider.alicloud v1.31.0

### Affected Resource(s)
- alicloud_disk_attachment

### Expected Behavior
`device_name` should return `/dev/vdb`

### Actual Behavior
`device_name` returns `/dev/xvdb`

### Steps to Reproduce
1. Create a ubuntu 16.04 64-bit VM
2. Create a disk (default disk category)
3. Attach that disk via
```
resource "alicloud_disk_attachment" "test" {
  disk_id       = "${alicloud_disk.test.id}"
  instance_id   = "${alicloud_instance.test.id}"
}
```
4. Get the output
``` 
output "disk_device_name" {
  value = "${alicloud_disk_attachment.test.device_name}"
}
```

### References
This might be a similar problem to that here in the BOSH CPI
- https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/issues/57

**Comment by xiaozhu36** [comment]
HI @cloudyday The release 1.47.0 has been fixed this issue. Please check it.
