### ISSUE TITLE
How to create a function with Aliyun Api Gateway service 

### ISSUE THREAD

**Issue by Quinton** [terraform-providers/terraform-provider-alicloud#791]
### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
- Aliyun Function Compute
- Aliyun Api Gateway

### Q
 How to create a function with Aliyun Api Gateway service by using terraform ?  Can you give an example？ Thank you

**Comment by xiaozhu36** [comment]
HI @Quinton This issue has been fixed by #811 . Please be patient.
