### ISSUE TITLE
The request processing has failed due to some unknown error, exception or failure.

### ISSUE THREAD

**Issue by toamitkumar** [terraform-providers/terraform-provider-alicloud#795]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.11
+ provider.alicloud v1.30.0

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_db_instance

### Terraform Configuration Files
```hcl
resource "alicloud_db_instance" "default" {
  engine           = "MySQL"
  engine_version   = "5.7"
  instance_type    = "mysql.n1.micro.1"
  instance_storage = "20"
  security_ips     = ["10.23.12.24"]
  instance_name    = "test"
}
```

### Debug Output
https://gist.github.com/toamitkumar/be7387fb28bddca86a1a24bee7daeb68

### Expected Behavior
RDS DB instance should have been created

### Actual Behavior
Exception thrown

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Refer HCL script above and do `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Note: I was able to create RDS with MySQL from the web console.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Nope, couldn't find one

**Comment by xiaozhu36** [comment]
HI @toamitkumar I am sorry for late reply. Does this issue still exist?

**Comment by xiaozhu36** [comment]
Closed by no reply
