### ISSUE TITLE
Parameter issue with resource `alicloud_vpn_gateway`

### ISSUE THREAD

**Issue by fboula** [terraform-providers/terraform-provider-alicloud#823]
Hi folks,

I found an issue/bad behavior of the `alicloud_vpn_gateway` resource. While trying to create a ipsec vnp gateway, I have errors if I dont specifically set the `ssl_connections` parameter to `0`.

The [provider documentation](https://www.terraform.io/docs/providers/alicloud/r/vpn_gateway.html) for this resource clearly define `ssl_connections` as **optional**.

### Terraform Version
```bash
Terraform v0.11.11
+ provider.alicloud v1.32.1
+ provider.random v2.0.0
```

### Affected Resource(s)
- alicloud_vpn_gateway

### Terraform Configuration Files
```hcl
resource "alicloud_vpn_gateway" "aliyun_vpn_gw" {
  name                 = "vpn-gw-aliyun"
  vpc_id               = "${alicloud_vpc.aliyun_vpc.id}"
  bandwidth            = "10"
  enable_ipsec         = true
  instance_charge_type = "PostPaid"
  description          = "Test VPN to GCP"
}

```

### Debug Output
```hcl
alicloud_vpn_gateway.aliyun_vpn_gw: Creating...
  bandwidth:            "" => "10"
  business_status:      "" => "<computed>"
  description:          "" => "Test VPN to GCP"
  enable_ipsec:         "" => "true"
  enable_ssl:           "" => "false"
  instance_charge_type: "" => "PostPaid"
  internet_ip:          "" => "<computed>"
  name:                 "" => "vpn-gw-aliyun"
  ssl_connections:      "" => "5"
  status:               "" => "<computed>"
  vpc_id:               "" => "vpc-xxx"
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (10s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (20s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (30s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (40s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (50s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (1m0s elapsed)
alicloud_vpn_gateway.aliyun_vpn_gw: Still creating... (1m10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* alicloud_vpn_gateway.aliyun_vpn_gw: 1 error(s) occurred:

* alicloud_vpn_gateway.aliyun_vpn_gw: Create Vpn got an error: &errors.ServerError{httpStatus:400, requestId:"65A64C44-8FD8-4190-8E74-66B08B175A6B", hostId:"vpc.aliyuncs.com", errorCode:"UnnecessarySslConnection", recommend:"", message:"The SSL connection is unnecessary for ssl vpn disabled.", comment:""}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```
See debug output here:
- https://gist.github.com/fboula/d7cb1909850abfe18bb960004652c906

### Expected Behavior
When using the argument `enable_ipsec = true` the provider should set the argument `ssl_connections` to **0** and create the vpn_gateway properly.

### Actual Behavior
When using the argument `enable_ipsec = true` the provider sets the argument `ssl_connections` to **5** and the creation of the vpn_gateway fails due to an API error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Define a resource `alicloud_vpn_gateway` with the argument `enable_ipsec` set to true.
2. `terraform apply`

### Workaround
I can create my resources with this declaration:
```hcl
resource "alicloud_vpn_gateway" "aliyun_vpn_gw" {
  name                 = "vpn-gw-aliyun"
  vpc_id               = "${alicloud_vpc.aliyun_vpc.id}"
  bandwidth            = "10"
  enable_ipsec         = true
  ssl_connections      = 0
  instance_charge_type = "PostPaid"

  description = "Test VPN to GCP"
}
```

**Comment by xiaozhu36** [comment]
HI @fboula This issue has been fixed by #822 Please be patient.

**Comment by fboula** [comment]
hi @xiaozhu36, thanks for your response, I didn't saw any issue so I fought it could help you. Nice work :+1:

**Comment by xiaozhu36** [comment]
HI @fboula I think the new release 1.33.0 has fixed it. Please check it and close this issue if there is no any other issues.
