### ISSUE TITLE
Refreshing state client timeout

### ISSUE THREAD

**Issue by DimiDimov** [terraform-providers/terraform-provider-alicloud#832]
Hi there,

I always run the same set of terraform templates for alibaba with only changing the image-id of the VMs. Sometimes (around 30% of the time) when I run terraform apply it almost completes the run but when it gets to destroying and is refreshing the state of the security group rules it runs into this error:

 alicloud_security_group_rule.allow_ssh: Refreshing state... (ID: sg-aaaaaaaaaaaaaaaaaaaa:ingress:tcp:1/65535::10.#.#.#/24:accept:1)
 
 Error: Error refreshing state: 3 error(s) occurred: 
 * alicloud_security_group_rule.allow_ssh_2: 1 error(s) occurred: 
 * alicloud_security_group_rule.allow_ssh_2: alicloud_security_group_rule.allow_ssh_2: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group_rule.go:176:
net/http: request canceled (Client.Timeout exceeded while reading body)
 * alicloud_security_group_rule.allow_ssh_20: 1 error(s) occurred: 
 * alicloud_security_group_rule.allow_ssh_20: alicloud_security_group_rule.allow_ssh_20: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_security_group_rule.go:176:
 net/http: request canceled (Client.Timeout exceeded while reading body)
 * data.alicloud_zones.zones_ds: 1 error(s) occurred: 
 * data.alicloud_zones.zones_ds: data.alicloud_zones.zones_ds: Error DescribeAvailableResource: &http.httpError{err:"net/http: request canceled (Client.Timeout exceeded while reading body)", timeout:true}

This is running on terraform: Terraform v0.11.11
alicloud provider: terraform-provider-alicloud_1.31.0_linux_amd64

An unique thing about my setup is that there are about 28 security group rules in the security group.

**Comment by xiaozhu36** [comment]
HI @DimiDimov I am sorry for late reply. I think this came from bad network environment. Does it still exist?

**Comment by DimiDimov** [comment]
It hasn't happened in 15 days so far so it might have gone away. Probably can close this issue then I'll reopen a new one if it comes back and I have reason to believe it's not a network issue.

**Comment by xiaozhu36** [comment]
Ok. Thanks.
