### ISSUE TITLE
Support using OSS as a backend

### ISSUE THREAD

**Issue by veysiertekin** [terraform-providers/terraform-provider-alicloud#944]
Support OSS as a backend like S3 ( https://www.terraform.io/docs/backends/types/s3.html )

**Comment by xiaozhu36** [comment]
We are waiting the [PR](https://github.com/hashicorp/terraform/pull/16927) to be merged.

**Comment by xiaozhu36** [comment]
HI @veysiertekin The terraform version 0.12.2 has supported it. Please check it.
