### ISSUE TITLE
Is Memory usage a supported metric for an ESS alarm?

### ISSUE THREAD

**Issue by w0rldart** [terraform-providers/terraform-provider-alicloud#961]
Hi,

Been trying to implement a Memory usage based alarm for an ESS setup, but it seems that the keyword I've tried are not supported

```
metric_name = "MemoryUsage"
#metric_name = "Memory"
```

Is it not supported?

### Terraform Version
`v0.11.13`

### Affected Resource(s)
`alicloud_ess_alarm`

### Debug Output
https://gist.github.com/w0rldart/a1e30177a603bb5711a547b9af861a29

**Comment by TalentNing** [comment]
@w0rldart  Valid metric names:
CpuUtilization
MemoryUtilization
ClassicInternetRx
ClassicInternetTx
IntranetRx
IntranetTx
For these metric_name above, you do not need to care about the dimension of specific metric, but for some metric, like MemoryUtilization， CMS agent is needed to collect metric data, and this is done automatically.

Sorry for the lack of documentation，These alarm apis are beta versions.

**Comment by w0rldart** [comment]
Thank you! That's perfect
