### ISSUE TITLE
Error creating alicloud_vpn_connection

### ISSUE THREAD

**Issue by jasminewu229** [terraform-providers/terraform-provider-alicloud#996]
Error: Error applying plan:

1 error(s) occurred:

* alicloud_vpn_connection.ipsec_connection: 1 error(s) occurred:

* alicloud_vpn_connection.ipsec_connection: SDK.ServerError
ErrorCode: UnknownError
Recommend:
RequestId: CC75AB7E-991F-4EB2-AFAB-5B9C40F8387B
Message: The request processing has failed due to some unknown error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

The .tf file is:

resource "alicloud_vpn_connection" "ipsec_connection" {
	name = "${var.ipsec_connection_name}"
    vpn_gateway_id = "${alicloud_vpn_gateway.vpn_gw.id}"
    customer_gateway_id = "${alicloud_vpn_customer_gateway.cs_gw.id}"
    local_subnet = ["${var.local_subnet}"]
    remote_subnet = ["${var.remote_subnet}"]
    effect_immediately = true
    ike_config = [{
        ike_auth_alg = "${var.ike_auth_alg}"
        ike_enc_alg = "${var.ike_enc_alg}"
        ike_version = "ikev2"
        ike_mode = "main"
        ike_lifetime = 86400
        psk = "${var.psk}"
        ike_pfs = "group2"
        }
    ]
    ipsec_config = [{
        ipsec_pfs = "group2"
        ipsec_enc_alg = "${var.ipsec_enc_alg}"
        ipsec_auth_alg = "${var.ipsec_auth_alg}"
        ipsec_lifetime = 86400
    }]
}

**Comment by ali-zhuyu** [comment]
This is a parameter passing bug. We have fixed it. See the link below for details.
[bugfix](https://github.com/terraform-providers/terraform-provider-alicloud/commit/ae9bba4496131c33c4fc70e831893cc7dc6a4cbb
)
We will release this bugfix on April 15 at the latest.

**Comment by xiaozhu36** [comment]
HI @jasminewu229 I am sorry. There is some reason results in postpone publishing the new release. I will let you know if the new release is published.

**Comment by jasminewu229** [comment]
What's the new ETA?

**Comment by xiaozhu36** [comment]
HI @jasminewu229 I think the release 1.40.0 has been fixed it. Can you check it?

**Comment by jasminewu229** [comment]
it's been fixed. I can confirm. Thank you!
